<?
require_once('Core.php');
?><?= Template::Header(['title' => '10. Art - The Standard Ebooks Manual', 'highlight' => 'contribute', 'manual' => true]) ?>
	<main>
		<article class="manual">

	<section data-start-at="10" id="art">
		<h1>Art</h1>
		<p>When you create a new Standard Ebooks draft using the <code class="bash">se create-draft</code> tool, you’ll already have templates for the cover and titlepage images present in <code class="path">./images/</code>.</p>
		<p>Text in these SVG files is represented as text, not paths, so you can edit them using a text editor and not an SVG editor. Then, the <code class="bash">se build-images</code> tool converts these text-based source images into path-based compiled images, for distribution in the final epub file. We do this so to avoid having to distribute the font files along with the epub.</p>
		<p>To develop cover and titlepage images, you must have the free <a href="https://github.com/theleagueof/league-spartan">League Spartan</a> and <a href="https://github.com/theleagueof/sorts-mill-goudy">Sorts Mill Goudy</a> fonts installed on your system.</p>
		<section id="complete-list-of-files">
			<h2>Complete list of files</h2>
			<p>A complete set of image source files consists of:</p>
			<ul>
				<li><code class="path">./images/cover.source.jpg</code>: The full source image used for the cover art, in as high a resolution as possible. Can be of any image format, but typically we end up with JPGs.</li>
				<li><code class="path">./images/cover.jpg</code>: A cropped part of the source image that will serve as the actual image file we use in the cover. Must be exactly 1400w × 2100h.</li>
				<li><code class="path">./images/cover.svg</code>: The SVG source file for the cover, with any text represented as actual, editable text. Must be exactly 1400w × 2100h pixels. Since the final cover image SVG has the text converted to paths, we keep this file around to make it easier to make changes to the cover in the future.</li>
				<li><code class="path">./src/epub/images/cover.svg</code>: The final SVG cover image. This image should be exactly like <code class="path">./images/cover.svg</code>, but with the text converted to paths.
					<p>This image is generated by the <code class="bash">se build-images</code> tool.</p>
				</li>
				<li><code class="path">./images/titlepage.svg</code>: The SVG source file for the titlepage, with any text represented as actual, editable text. Must be exactly 1400 pixels wide, but the height must exactly match the text height plus some padding (described below).</li>
				<li><code class="path">./src/epub/images/titlepage.svg</code>: The final SVG titlepage image, with text converted to paths just like the cover page.
					<p>This image is generated by the <code class="bash">se build-images</code> tool.</p>
				</li>
			</ul>
		</section>
		<section id="svg-patterns">
			<h2>SVG patterns</h2>
			<ol type="1">
				<li>SVGs are only sized with <code class="html">viewBox</code>, not <code class="html">height</code> or <code class="html">width</code>.
					<ol type="1">
						<li>The <code class="html">viewBox</code> attribute consists of whole numbers, without fractions.</li>
					</ol>
				</li>
				<li>The only attributes on the <code class="html"><span class="p">&lt;</span><span class="nt">svg</span><span class="p">&gt;</span></code> root element are: <code class="html">xmlns</code>, <code class="html">version</code>, and <code class="html">viewBox</code>.</li>
				<li>The contents of the SVG’s <code class="html"><span class="p">&lt;</span><span class="nt">title</span><span class="p">&gt;</span></code> element matches the <code class="html">alt</code> attribute of its <code class="html"><span class="p">&lt;</span><span class="nt">img</span><span class="p">&gt;</span></code> element in the text.</li>
				<li>Grouping with <code class="html"><span class="p">&lt;</span><span class="nt">g</span><span class="p">&gt;</span></code> is avoided, unless it makes semantic sense. Groups whose sole purpose is to apply transforms should have those transforms applied to the children, and the group removed.</li>
				<li>The use of fill color is avoided unless strictly necessary. Not defining a fill color allows for night mode compatibility.</li>
				<li>The <code class="html">transform</code> attribute is illegal; transforms are applied to their elements directly.</li>
			</ol>
		</section>
		<section id="the-cover-image">
			<h2>The cover image</h2>
			<aside class="warning">
				<p>The SE Editor-in-Chief must review and approve of the cover art you select before you can commit it to your repository.</p>
				<p><strong>Do not commit cover art without contacting the mailing list first!</strong></p>
			</aside>
			<p>The cover image is auto-generated by the <code class="bash">se create-draft</code> tool. The arrangement of the text is a suggestion, and may be changed by the producer in case a more visually-pleasing arrangment is desired.</p>
			<p>After completing <code class="path">./images/cover.svg</code>, use the <code class="bash">se build-images</code> tool to build the rasterized distribution SVG in <code class="path">./src/epub/images/cover.svg</code>.</p>
			<section id="cover-image-layout">
				<h3>Cover image layout</h3>
				<p><code class="bash">se create-draft</code> generates <code class="path">./images/cover.svg</code> for you with correct dimensions and layout. It’s rarely necessary to edit the cover.</p>
				<ol type="1">
					<li>Both the title and author are in League Spartan font with 5px letter spacing in ALL CAPS.</li>
					<li>The left and right sides of the black title box have at least 40px padding. More padding is preferrable over cramming the title in.</li>
					<li>Translators, illustrators, and other contributors besides the author do not appear on the cover.</li>
					<li>The group of both the title and author lines is horizontally centered in the black title box.</li>
				</ol>
				<section id="title-line-dimensions">
					<h4>Title line dimensions</h4>
					<ol type="1">
						<li>One-line titles: the line is 80px tall. Example: <i><a href="/ebooks/niccolo-machiavelli/the-prince/w-k-marriott">The Prince</a></i>, by Niccolò Machiavelli.</li>
						<li>Two-line titles: each line is 80px tall, and the second title line is 20px below the first line. Example: <i><a href="/ebooks/fyodor-dostoevsky/crime-and-punishment/constance-garnett">Crime and Punishment</a></i>, by Fyodor Dostoevsky.</li>
						<li>Two-line, very long titles: each line is 60px tall, and the second line is 20px below the first line. Example: <i><a href="/ebooks/selma-lagerlof/the-wonderful-adventures-of-nils/velma-swanston-howard">The Wonderful Adventures of Nils</a></i>, by Selma Lagerlöf.</li>
						<li>Two-line, extremely long titles: each line is 50px tall, and the second line is 20px below the first line. Example: <i><a href="/ebooks/rudolph-erich-raspe/the-surprising-adventures-of-baron-munchausen">The Surprising Adventures of Baron Munchausen</a></i>, by Rudolph Erich Raspe.</li>
					</ol>
				</section>
				<section id="author-line-dimensions">
					<h4>Author line dimensions</h4>
					<ol type="1">
						<li>The first author line begins 60px below the last title line.</li>
						<li>One-line authors: the line is 40px tall.</li>
						<li>Two-line authors: each line is 40px tall, and the second author line is 20px below the first line.</li>
					</ol>
				</section>
			</section>
			<section id="cover-art">
				<h3>Cover art</h3>
				<ol type="1">
					<li><code class="path">./images/cover.svg</code> links to <code class="path">./images/cover.jpg</code> as the canvas background.</li>
					<li><code class="path">./images/cover.jpg</code> is 1400w × 2100h in pixels, and is compressed as much as possible while maintaining an acceptable image quality. An acceptable level of image quality is more important than file size.</li>
					<li>Because <code class="path">./images/cover.jpg</code> is an image with large dimensions, it must be sourced from a high-resolution scan. It may not always be possible to locate a high-resolution scan, so a smaller source image may be upscaled <em>a small amount</em> to meet the target dimensions.</li>
					<li>Cover art is in the “fine art oil painting” style. Art not in this style, like modern CG art, is not acceptable.</li>
					<li><code class="path">./images/cover.source.svg</code> is the unmodified source image used to create <code class="path">./images/cover.jpg</code>. This image is kept in case changes to the source images are to be made in the future.</li>
				</ol>
				<section id="us-pd-clearance">
					<h4>US-PD clearance</h4>
					<p>The paintings we use are all in the U.S. public domain (US-PD). Your task is to locate a painting suitable for the kind of book you’re producing, and then demonstrate that the painting is indeed in the U.S. public domain.</p>
					<p>U.S. copyright law is complicated. Because of this, <strong>we require that you provide a link to a page scan of a 1924-or-older book that reproduces the painting you selected.</strong> <em>This is a hard requirement</em> to demonstrate that the painting you selected is in fact in the U.S. public domain. Just because a painting is very old, or Wikipedia says it’s PD, or it’s PD in a country besides the U.S., doesn’t necessarily mean it actually <em>is</em> PD in the U.S.</p>
					<section id="clearance-procedure">
						<h5>Clearance procedure</h5>
						<p>To actually demonstrate that a painting is PD, you must locate a reproduction of that painting in a 1924-or-older book.</p>
						<p>This can be quite difficult. Many people find this to be the most time-consuming part of the ebook production process.</p>
						<p>Because of the difficulty, finding suitable cover at is <em>all about compromise</em>. You’re unlikely to find the perfect cover image. You’ll find a lot of paintings that would be great matches, but that you can’t find reproductions of and thus we can’t use. So, be ready to compromise.</p>
						<p>Note that in <code class="path">./images/cover.svg</code>, the black title and author box always goes in the lower half of the work. Thus, paintings in which some important detail would be obscured by the box cannot be used.</p>
						<ul>
							<li>Before you can go looking for a reproduction of a specific painting to prove its PD status, you have to find a suitable painting to begin with. <a href="https://www.wikiart.org/">Wikiart.org</a> is a great resource to search for paintings by keyword. Museum online collections are another good place to look for inspiration.
								<p>Once you find a potential candidate you can start researching its PD status.</p>
							</li>
							<li>Many museum online catalogs have a “bibliography” or “references” section for each painting in their collection. This is usually a list of books in which the painting was either mentioned or reproduced. This is a good shortcut to finding the names of books in which a painting was reproduced, and if you’re lucky, a search for the book title in Google Books will turn up scans.</li>
							<li>Visit <a href="https://books.google.com/">Google Books</a>, <a href="https://www.hathitrust.org">HathiTrust</a>, and the <a href="https://archive.org">Internet Archive</a> to begin searching for books where your art is reproduced.
								<p>(Note that if your IP address is not in the U.S., many book archives like Google Books and HathiTrust may disable book previews.)</p>
								<p>When searching for cover art, remember that artist names and painting titles may be spelled in many different ways. Often a painting went by multiple titles, or if the title was not in English, by many different translations. Your best bet is to simply search for an artist’s last name, and not the painting title.</p>
							</li>
							<li>Once you locate a book with reproductions, open the book up in thumbnail view and quickly eyeball the pages to see if the artwork is reproduced there.</li>
						</ul>
						<section id="gotchas">
							<h6>Gotchas</h6>
							<ul>
								<li>In older books it was common to have <em>etchings</em> of paintings. Etchings are not strict reproductions, and so we cannot count them for PD clearance.
									<p>Additionally, it was common for painters to produce several different versions of the same artwork. These different versions are also not enough for PD clearance. The version you find in print must exactly match the scan you located online.</p>
									<p>Before completing PD clearance, carefully compare the reproduction in the page scan with the high-resolution scan to ensure they are the same painting. Small details like the position of trees, clouds, reflections, or water are good ways to check if the painting is identical, or if you’re looking at a different version.</p>
								</li>
								<li>Sometimes the catalog record for a book has an incorrect publication year. Please verify the page scan of the copyright page to ensure the book is 1924 or older.</li>
							</ul>
						</section>
					</section>
					<section id="resources-for-locating-high-resolution-scans">
						<h5>Resources for locating high resolution scans</h5>
						<ul>
							<li><a href="https://commons.wikimedia.org">Wikimedia Commons</a></li>
							<li><a href="https://www.google.com/culturalinstitute/project/art-project">Google Art Project</a></li>
							<li><a href="https://www.wikiart.org">WikiArt</a></li>
						</ul>
					</section>
					<section id="resources-for-locating-print-reproductions">
						<h5>Resources for locating print reproductions</h5>
						<ul>
							<li><a href="https://books.google.com">Google Books</a>
								<p><a href="https://www.google.com/webhp?tbs=cdr:1,cd_min:,cd_max:1924&amp;amp;tbm=bks">Use this shortcut</a> to search for books that were published in 1924 or earlier.</p>
								<p>Google Books is a convenient first stop because its thumbnail view is very fast, and it does a better job of highlighting search results than HathiTrust or Internet Archive.</p>
							</li>
							<li><a href="https://www.hathitrust.org">HathiTrust</a>
								<p><a href="https://babel.hathitrust.org/cgi/ls?a=srchls&amp;amp;anyall1=all&amp;amp;q1=&amp;amp;field1=ocr&amp;amp;op3=AND&amp;amp;yop=before&amp;amp;pdate_end=1924">Use this shortcut</a> to search for books that were published in 1924 or earlier.</p>
							</li>
							<li><a href="https://archive.org">Internet Archive</a>
								<p><a href="https://archive.org/search.php?query=+date%3A%5B1850-01-01+TO+1924-12-31%5D&amp;amp;sin=TXT&amp;amp;sort=-date">Use this shortcut</a> to search for books that were published in 1924 or earlier.</p>
							</li>
							<li>Our own <a href="uncategorized-art-resources">list of uncategorized art books</a> may be helpful to browse through for inspiration and easy US-PD clearance.</li>
						</ul>
					</section>
					<section id="museums-with-cc0-collections">
						<h5>Museums with CC0 collections</h5>
						<p>Images that are explicitly marked as CC0 from these museums can be used without further research. Not all of their images are CC0; you must confirm the presence of a CC0 license on the specific image you want to use.</p>
						<ul>
							<li><a href="https://www.rijksmuseum.nl/en/search?q=&amp;f=1&amp;p=1&amp;ps=12&amp;type=painting&amp;imgonly=True&amp;st=Objects">Rijksmuseum</a> (Open the “Object Data” section and check they “Copyright” entry under the “Acquisition and right” section to confirm CC0)</li>
							<li><a href="https://www.europeana.eu/portal/en/collections/art?f%5BDATA_PROVIDER%5D%5B%5D=Finnish+National+Gallery&amp;f%5BREUSABILITY%5D%5B%5D=open&amp;f%5BRIGHTS%5D%5B%5D=http%2A%3A%2F%2Fcreativecommons.org%2F%2Apublicdomain%2Fzero%2A&amp;per_page=96&amp;view=grid">Finnish National Gallery via Europeana</a> (Use the “View at” link under the “Find out more” header to confirm CC0 license at the museum’s site)</li>
							<li><a href="https://www.metmuseum.org/art/collection/search#!/search?material=Paintings&amp;showOnly=withImage%7Copenaccess&amp;sortBy=Relevance&amp;sortOrder=asc&amp;perPage=20&amp;offset=0&amp;pageSize=0">Met Museum</a> (CC0 items have the CC0 logo under the image)</li>
							<li><a href="https://www.nationalmuseum.se/en/samlingarna/fria-bilder">National Museum Sweden</a> (CC-PD items have the CC-PD mark in the lower left of the item’s detail view)</li>
							<li><a href="https://collections.artsmia.org/">Minneapolis Institute of Art</a> (Public domain items are listed as such under “Rights”)</li>
							<li><a href="https://art.thewalters.org/">The Walters Art Museum</a> (Public domain items are listed as "CC Creative Commons License" which links to a CC0 rights page)</li>
							<li><a href="https://www.artic.edu/collection?q=test&amp;is_public_domain=1&amp;department_ids=European+Painting+and+Sculpture">Art Institute of Chicago</a> (CC0 items say CC0 in the lower left of the painting in the art detail page)</li>
							<li><a href="http://www.clevelandart.org/art/collection/search?only-open-access=1&amp;filter-type=Painting">Cleveland Museum of Art</a> (CC0 items have the CC0 logo near the download button.)</li>
							<li><a href="http://parismuseescollections.paris.fr/en/recherche/image-libre/true/avec-image/true/denominations/peinture-166168?mode=mosaique&amp;solrsort=ds_created%20desc">Paris Musées</a> (CC0 items have the CC0 logo near the download button.)</li>
							<li><a href="https://www.si.edu/search/collection-images?edan_q=landscape&amp;edan_fq[0]=object_type%3A&#34;Paintings&#34;">The Smithsonian</a> (CC0 items say CC0 under the Usage header in the item details.)</li>
						</ul>
					</section>
					<section id="clearance-faq">
						<h5>Clearance FAQ</h5>
						<ul>
							<li><strong>I found a great painting, and Wikipedia says it’s public domain, but I can’t find a reproduction in a book. Can I use it?</strong>
								<p>No. You must find a reproduction of your selected painting in a book published in 1924 or earlier.</p>
							</li>
							<li><strong>I found a great painting, and it’s really old, and the author died a long time ago, but I can’t find a reproduction in a book. Can I use it?</strong>
								<p>No. You must find a reproduction of your selected painting in a book published in 1924 or earlier.</p>
							</li>
							<li><strong>I’ve found a reproduction in a book, but the book is from 1925. Is that OK?</strong>
								<p>No. You must find a reproduction of your selected painting in a book published in 1924 or earlier.</p>
							</li>
							<li><strong>I’ve found scan on a random museum site. Is that OK?</strong>
								<p>No. You must find a reproduction of your selected painting in a book published in 1924 or earlier.</p>
							</li>
							<li><strong>But...</strong>
								<p>No. You must find a reproduction of your selected painting in a book published in 1924 or earlier.</p>
							</li>
						</ul>
					</section>
				</section>
			</section>
		</section>
		<section id="the-titlepage-image">
			<h2>The titlepage image</h2>
			<p>The titlepage image is auto-generated by the <code class="bash">se create-draft</code> tool. The arrangement of the text is a suggestion, and may be changed by the producer in case a more visually-pleasing arrangment is desired.</p>
			<p>After completing <code class="path">./images/titlepage.svg</code>, use the <code class="bash">se build-images</code> tool to build the rasterized distribution SVG in <code class="path">./src/epub/images/titlepage.svg</code>.</p>
			<section id="titlepage-image-layout">
				<h3>Titlepage image layout</h3>
				<ol type="1">
					<li>The title, author, other contributors are in League Spartan font with 5px letter spacing in ALL CAPS.</li>
					<li>The titlepage does not include subtitles.
						<p>For example, the titlepage would contain <code class="html">THE MAN WHO WAS THURSDAY</code>, but not <code class="html">THE MAN WHO WAS THURSDAY: A NIGHTMARE</code>.</p>
					</li>
					<li>Names of contributors besides the author are preceded by <code class="html">translated by</code> or <code class="html">illustrated by</code>. <code class="html">translated by</code> and <code class="html">illustrated by</code> are set in lowercase Sorts Mill Goudy Italic font.</li>
					<li>Only the author, translator, and illustrator are on the titlepage. Other contributors like writers of introductions or annotators are not included.</li>
					<li>The canvas has a padding area of 50px vertically and 100px horizontally in which text must not enter.</li>
					<li>The viewbox width is exactly 1400px wide.</li>
					<li>The viewbox height must <em>precisely fit the titlepage contents, plus 50px padding</em>.</li>
				</ol>
				<section id="id1">
					<h4>Title line dimensions</h4>
					<ol type="1">
						<li>Each title line is 80px tall.</li>
						<li>The title is split into as many lines as necessary to fit.</li>
						<li>Title lines are separated by a 20px margin between each line.</li>
					</ol>
				</section>
				<section id="id2">
					<h4>Author line dimensions</h4>
					<ol type="1">
						<li>The first author line begins 100px below the last title line.</li>
						<li>Each author line is 60px tall.</li>
						<li>If an author line must be split, the next line begins 20px below the previous one.</li>
						<li>For works with multiple authors, subsequent author lines begin 20px below the last author line.</li>
					</ol>
				</section>
				<section id="contributor-lines-dimensions">
					<h4>Contributor lines dimensions</h4>
					<ol type="1">
						<li>“Contributors” are a “contributor descriptor,” like <code class="html">translated by</code>, followed by the contributor name on a new line.</li>
						<li>The first contributor descriptor line begins 150px below the last author line.</li>
						<li>Contributor descriptor lines are 40px tall, all lowercase, in the Sorts Mill Goudy Italic font.</li>
						<li>The contributor name begins 20px below the contributor descriptor line.</li>
						<li>The contributor name is 40px tall, ALL CAPS, in the League Spartan font.</li>
						<li>If there is more than one contributor of the same type (like multiple translators), they are listed on one line. If there are two, separate them with <code class="html">AND</code>. If there are more than two, separate them with commas, and <code class="html">AND</code> after the final comma. Example: <i><a href="/ebooks/hermann-hesse/siddhartha/gunther-olesch_anke-dreher_amy-coulter_stefan-langer_semyon-chaichenets">Siddhartha</a></i>, by Hermann Hesse.</li>
						<li>If there is more than one contributor type (like both a translator and an illustrator), the next contributor descriptor begins 80px after the last contributor name.</li>
					</ol>
				</section>
			</section>
		</section>
	</section>
		</article>
	</main>
<?= Template::Footer() ?>