<?
require_once('Core.php');
?><?= Template::Header(['title' => '3. The Structure of an Ebook - The Standard Ebooks Manual', 'highlight' => 'contribute', 'manual' => true]) ?>
	<main>
		<article class="manual">

	<section data-start-at="3" id="the-structure-of-an-ebook">
		<h1>The Structure of an Ebook</h1>
		<!-- An introduction is required for the data-start-at class to take effect. -->
		<p>Books consist of three major partitions: Front Matter, Body Matter, and Back Matter.</p>
		<p>These terms become important when building the Table of Contents (ToC). The Landmarks section of the ToC requires items to be labeled with the appropriate partition identifier. See <a href="/manual/1.0.0/table-of-contents-patterns.html">ToC Patterns</a> for more information about the ToC.</p>
		<section id="front-matter">
			<h2>Front matter</h2>
			<p>Front matter is material that appears before the main content of the work. It includes such items as a dedication, an epigraph, an introduction, and so on.</p>
			<section id="cover">
				<h3>Cover</h3>
				<p>The cover presents the outer appearance of the book, usually consisting of an image, the title of the book and the author’s name. For Standard Ebooks productions, the cover is an SVG image generated from template that combines the book title and author, and a background image. The <code class="path">se build-images</code> tool generates the cover image used for distribution.</p>
			</section>
			<section id="title-page">
				<h3>Title page</h3>
				<p>The title page lists the title of the book and the author’s name. For Standard Ebooks productions, the title page contains an SVG image generated by the <code class="path">se create-draft</code> tool, which is then compiled for distribution using the <code class="path">se build-images</code> tool.</p>
			</section>
			<section id="imprint">
				<h3>Imprint</h3>
				<p>The imprint contains information about the publisher of the book. For Standard Ebooks productions, a template file is provided and the producer modifies it to suit the particular ebook.</p>
			</section>
			<section id="dedication">
				<h3>Dedication</h3>
				<p>An inscription at the start of a work and is usually a tribute to some person or persons whom the author wishes to honor.</p>
			</section>
			<section id="epigraph">
				<h3>Epigraph</h3>
				<p>A quotation or poem at the start of a book which may set the mood or inspire thoughts about the work to come.</p>
				<p>If the epigraph is a poem or quotation from poetry, it must follow the standards for verse described in <a href="/manual/1.0.0/high-level-structural-patterns.html">High-Level Structural Patterns</a></p>
			</section>
			<section id="acknowledgements">
				<h3>Acknowledgements</h3>
				<p>A list of persons or organizations whom the author wishes to thank, generally for helping with the creation of the book. The acknowledgements can also be part of the back matter of the book, depending on where the author placed them.</p>
			</section>
			<section id="foreword">
				<h3>Foreword</h3>
				<p>A preliminary section containing information about the book, generally written by someone other than the author.</p>
			</section>
			<section id="preface">
				<h3>Preface</h3>
				<p>A preliminary section which states the subject of the book and its aims, generally written by the author of the work.</p>
			</section>
			<section id="introduction">
				<h3>Introduction</h3>
				<p>An introduction is typically found in non-fiction works. It is written by the book’s author and sets out the book’s main argument.</p>
			</section>
			<section id="half-title">
				<h3>Half title</h3>
				<p>In books which include front matter, the half title page marks the start of the body matter.</p>
				<ol type="1">
					<li>The half title lists the title of the book, but not the author.</li>
					<li>A half title is required if there is any front matter in the book.</li>
				</ol>
			</section>
			<section id="table-of-contents">
				<h3>Table of Contents</h3>
				<p>Also known as the “ToC.” The Table of Contents lists the main headings in the book. In traditionally printed books, the table of contents is part of the front matter of the book.</p>
				<ol type="1">
					<li>In Standard Ebooks productions, the table of contents is omitted from the ebook’s spine and is instead presented to the reader via their ereader’s ToC feature.</li>
				</ol>
			</section>
		</section>
		<section id="body-matter">
			<h2>Body matter</h2>
			<p>The body matter is the main content of the book. It is typically divided into chapters, or in the case of a collection, individual stories, poems, or articles. It may be structured at the highest level into larger divisions such as volumes or parts. Besides the contents of the book itself, it may also include:</p>
			<section id="prologue">
				<h3>Prologue</h3>
				<p>A prologue is generally found only in works of fiction. It may introduce characters, set up background information, or bring forward a critical part of the action to which the story leads.</p>
				<p>A prologue is generally part of the body matter, unless the prologue is a fictional element of a frame narrative. In that case, it may be appropriate to place it in front of the half title and give it a different title, while keeping the <code class="html">prologue</code> semantic inflection.</p>
			</section>
			<section id="epilogue">
				<h3>Epilogue</h3>
				<p>An epilogue is generally found only in works of fiction. It typically winds up the action or briefly tells the subsequent history of major characters. An epilogue should therefore have similar structure to the chapters of a book.</p>
			</section>
		</section>
		<section id="back-matter">
			<h2>Back matter</h2>
			<p>Back matter is material which follows the main content, but could be separated from the main content. It might include endnotes, an appendix, an afterword, a colophon, and so on.</p>
			<section id="afterword">
				<h3>Afterword</h3>
				<p>A concluding section of a book, typically but not necessarily written by the author, which stands outside the main story of a work of fiction, or the main argument of a work of non-fiction. It may add additional information or comment on the book and its production.</p>
			</section>
			<section id="list-of-illustrations">
				<h3>List of Illustrations</h3>
				<p>Also known as the “LoI,” the list of illustrations is an index to the illustrations in a book. The items are included as part of a list and linked to the points in the text where the illustration appears.</p>
			</section>
			<section id="endnotes">
				<h3>Endnotes</h3>
				<p>A list of notes to the text. Each item is given a unique sequential number and linked to the point in the text to which the note refers. If the text originally has footnotes, they are converted to endntoes.</p>
			</section>
			<section id="colophon">
				<h3>Colophon</h3>
				<p>The colophon contains information about the publisher of the book, the author, the original publication date, the edition, its publication date, the cover artist and other information relevant to the particular release of a book. A Standard Ebooks colophon is standardized and follows a common pattern.</p>
			</section>
			<section id="copyright-page">
				<h3>Copyright Page</h3>
				<p>The copyright page includes information about the copyright status of the work. All Standard Ebooks are in the US Public domain, and use a standardized “copyright” page to explain this.</p>
				<p>Copyright pages are usually part of the front matter of a book, but in the case of Standard Ebooks productions they are back matter, and the last item in the book.</p>
			</section>
		</section>
	</section>
		</article>
	</main>
<?= Template::Footer() ?>