<?
$carousel = Ebook::GetAllBySet([13, 833, 376]);
?>
<?= Template::Header(title: 'Aesop’s Fabulous Nature', css: ['/css/blog.css']) ?>
<main>
	<section class="narrow blog">
		<nav class="breadcrumbs"><a href="/blog">Blog</a> →</nav>
		<h1>Aesop’s Fabulous Nature</h1>
		<p class="byline">By Erin Endrei</p>
		<?= Template::DonationCounter() ?>
		<?= Template::DonationProgress() ?>
		<div class="editors-note">
			<p>This article first appeared in the July 2025 edition of our <a href="/newsletter">email newsletter</a>.</p>
		</div>
		<p>While it’s not certain that Aesop existed, the fables attributed to him might be the most popular tales ever told. They were common knowledge by the classical period of ancient Greece: the playwright <a href="/ebooks/aristophanes">Aristophanes</a> mentions them, and in Plato’s <a href="/ebooks/plato/dialogues/benjamin-jowett/text/phaedo#phaedo-text"><i>Phaedo</i></a> Socrates is shown versifying them before his death.</p>
		<p>Most of us probably associate the fables we know with our childhoods, and with particular moral lessons. But their use as didactic nursery stories is comparatively recent—at least compared to their estimated age. The original “fables” consists of numerous ancient and medieval manuscripts in several different languages, primarily Latin and Greek. There may have been written compilations of the fables by the 4th century BC, but the earliest extant collections date from the first century AD.</p>
		<p>The phrase “Aesop’s fables” is then in one sense a misnomer, as there’s no single primary source for them; and if Aesop even existed, then he, like Socrates, probably wrote nothing down. It’s more accurate to speak of “Aesopic” fables, where the adjective marks a genre or tradition. In 1952 the classicist Benjamin Perry published the first comprehensive scholarly edition of sources, <i>Aesopica</i>, which presents transcriptions of the most important Greek and Latin fables. His enumeration of them, the Perry Index, is still today’s standard.</p>
		<p>At Standard Ebooks we host the <a href="/ebooks/aesop/fables/v-s-vernon-jones">translation published in 1912 by V. S. Vernon Jones</a>, a Cambridge classicist, with an introduction by <a href="/ebooks/g-k-chesterton">G. K. Chesterton</a>. Unfortunately, next to no information is available about either the translator or the publication of the edition, including how Chesterton came to write the introduction to it. One interesting anecdote that did emerge is that <a href="/ebooks/james-joyce">James Joyce</a> owned a copy, <a href="https://www.jstor.org/stable/26285214">according to the scholar Sam Slote</a>.</p>
		<p>What Vernon Jones’s edition is a translation <em>of</em> is also a question that’s more difficult to answer than it might first appear, as it predates Perry’s <i>Aesopica</i> by some four decades and contains no explanatory matter. But comparing our collection with the most comprehensive modern edition, that by <a href="http://mythfolklore.net/aesopica/index.htm">Laura Gibbs for Oxford World’s Classics</a>, suggests that Vernon Jones translated a mixture of Greek and Latin sources.</p>
		<p>Chesterton’s introduction is characteristically engaging; still, it seems worth noting that it, at one point, misrepresents the fables by claiming that the distinguishing mark of fable is containing only animal characters, and never human beings. On the contrary, many Aesopic fables feature the latter, sometimes as main characters. To see for yourself, skim the <a href="/ebooks/aesop/fables/v-s-vernon-jones/text">Table of Contents of Vernon Jones’s translation</a>, where you’ll see examples like <a href="/ebooks/aesop/fables/v-s-vernon-jones/text/fables#the-flea-and-the-man">The Flea and the Man</a>, <a href="/ebooks/aesop/fables/v-s-vernon-jones/text/fables#the-blind-man-and-the-cub">The Blind Man and the Cub</a>, <a href="/ebooks/aesop/fables/v-s-vernon-jones/text/fables#the-boy-and-the-snails">The Boy and the Snails</a>, and many more.</p>
		<p>The claim that there are no human beings in the fables is connected to what Chesterton considers the most important thing about them: their <em>didactic potential</em>. He writes:</p>
		<blockquote>
			<p>This is the immortal justification of the Fable: that we could not teach the plainest truths so simply without turning men into chessmen. We cannot talk of such simple things without using animals that do not talk at all.</p>
		</blockquote>
		<p>There’s reason to doubt this thesis beyond just the fact that many Aesopic fables contain human beings: for if human beings can’t feature in a story intended to deliver truths <em>about</em> human beings, then it seems natural to ask whether it’s a plain and simple truth about human beings that’s being delivered in the first place—or something else.</p>
		<p>James Joyce illustrated the possibility of questioning, or at least muddying, the moral of a fable, incorporating one of the best-known of them, “<a href="/ebooks/aesop/fables/v-s-vernon-jones/text/fables#the-grasshopper-and-the-ants">The Grasshopper and the Ants</a>,” into his final book, <i>Finnegans Wake</i>, which enters the US public domain in 2035. The grasshopper appears as the “Gracehoper” (grace, hope) and the ant as the “Ondt” (an adjective that in Norwegian means “bad,” “wicked,” or “evil”).</p>
		<p>In Slote’s article mentioned earlier, he considers this an example of “transvaluing values” in the spirit of <a href="/ebooks/friedrich-nietzsche">Friedrich Nietzsche’s</a> <i><a href="/ebooks/friedrich-nietzsche/the-genealogy-of-morals/horace-b-samuel">Genealogy of Morals</a></i>. The discussion in the article is rarefied, but Slote’s most relevant point is that “the fable … can always be construed differently.”</p>
		<p>That is, while the fables’ survival for around two and a half millennia is often attributed to their profound and timeless wisdom, the received moral of a fable can also strike us as disputable, or even invertible. There are three other related situations you’ll encounter if you read the Vernon Jones tranlation: fables whose morals appear inconsistent with one another, fables with no apparent moral, and fables with ambiguous or unclear morals.</p>
		<p>Such examples conflict with Chesterton’s notion that the fables teach a set of plain truths. They also call into question the stronger claim with which he ends his introduction, that “there is only one moral to the fables; because there is only one moral to everything.”</p>
		<p>This outlook is too simple, and is perhaps even suggested by one of them, when an <a href="/ebooks/aesop/fables/v-s-vernon-jones/text/fables#demades-and-his-fable">Athenian orator</a> contrasts listening to them with participation in public life. Like much that is boldly and simply stated (including many of Chesterton’s dicta) the fables’ value often lies in provoking thought not about <em>why they’re accurate</em>, because they’re often not, but about <em>why things aren’t so simple</em>. This is no small value!</p>
		<p>At the same time, the fables in Vernon Jones’s formal, sometimes stuffy translation are also often likely to provoke laughter. They present images both light and serious, amusing and sobering: something for both the grasshopper and the ant in human nature, which fable after fable <a href="/ebooks/aesop/fables/v-s-vernon-jones/text/fables#the-she-goats-and-their-beards">implies is fixed</a>, but then, for all that, <a href="/ebooks/aesop/fables/v-s-vernon-jones/text/fables#the-owl-and-the-birds">occasionally changeable</a>.</p>
		<h2 id="ebooks-in-this-newsletter">Free ebooks in this post</h2>
		<?= Template::EbookCarousel(carousel: $carousel) ?>
	</section>
</main>
<?= Template::Footer() ?>
