<?
$ebookIds = [1085, 1052];
$carousel = Db::Query('SELECT * from Ebooks where EbookId in ' . Db::CreateSetSql($ebookIds), $ebookIds, Ebook::class);
?>
<?= Template::Header(['title' => 'Death and Beauty in the Alps', 'css' => ['/css/blog.css'], 'highlight' => '', 'description' => '']) ?>
<main>
	<section class="narrow blog">
		<nav class="breadcrumbs"><a href="/blog">Blog</a> →</nav>
		<h1>Death and Beauty in the Alps</h1>
		<p class="byline">By Erin Endrei</p>
		<?= Template::DonationCounter() ?>
		<?= Template::DonationProgress() ?>
		<div class="editors-note">
			<p>This article first appeared in the February 2025 edition of our <a href="/newsletter">email newsletter</a>.</p>
		</div>
		<p>Edward Whymper’s <a href="https://standardebooks.org/ebooks/edward-whymper/scrambles-amongst-the-alps-in-the-years-1860-69">Scrambles Amongst the Alps in the Years 1860–69</a> recounts the first successful ascent of the Matterhorn, long believed inaccessible, and the last of the major Alpine peaks to be scaled by mountaineers.</p>
		<p>The triumph of Whymper’s eighth attempt on the mountain was famously followed by the tragedy of the descent: four of the party’s seven members fell to their deaths after a rope between guide Peter Taugwalder the elder and Lord Francis Hudson broke. The failed rope, Whymper discovered later, was so weak that it shouldn’t have been used. Worse, it didn’t need to have been be used: the party had had much stronger rope available to deploy.</p>
		<p>According to his account, Whymper hadn’t been there when the rope had been selected. After already falling behind the others in order to make sketches from the summit, on rejoining them he had been asked to go back again to place a bottle containing their names.</p>
		<p>An illustrator and engraver before he took up mountaineering as a sport, Whymper declares language inadequate to describe some of his experiences in the mountains; this is the reason he gives in the book’s first preface for including so many illustrations.</p>
		<p>Nevertheless, he specifies the circumstances of the accident with the precision that characterizes all his descriptions, whether concerning methods of tent-making, scientific disputations about glaciers, or the movement of fleas (“a party of whom executed a spirited fandango on my cheek, to the sound of music produced on the drum of my ear, by one of their fellows beating with a wisp of hay.”)</p>
		<p>The accident on the descent was describable, but only briefly: it was surely chief among the griefs mentioned in the book’s last paragraphs, upon which he “dared [not] to dwell.” “From the beginning think what may be the end,” is his closing advice to fellow mountaineers, and the final illustration of the main text depicts a man lying on his back, as his fallen comrades are described as having done, captioned “The end.”</p>
		<p>Whymper’s attitude to “the end” of the first successful ascent wasn’t just grief and regret, however, but bitterness. This is reflected in the penultimate chapter’s <a href="https://standardebooks.org/ebooks/edward-whymper/scrambles-amongst-the-alps-in-the-years-1860-69/text/chapter-21">epigraphs</a> from Euripides and Pliny, according to the latter of whom “the same actions are at one time attributed to earnestness and at another to vanity.” The choice to pursue an endeavour is often judged by its overt outcome; at the same time the contingency of outcomes is easily underestimated and probabilities misjudged.</p>
		<p>But previous attempts on the Matterhorn had already taught Whymper that scrutinizing the role of chance in an outcome doesn’t always yield conclusions in one’s favor: if he had been less lucky in 1862 <a href="https://standardebooks.org/ebooks/edward-whymper/scrambles-amongst-the-alps-in-the-years-1860-69/text/chapter-5#illustration-44">on a solo attempt</a>, he would have been killed by a violent fall down a gully. Lucky he was; but the vulnerability of ambition to the forces of chance would have been a fitting part of the meditation he says he made, following the near-fatal accident, on the “vanity of human wishes.”</p>
		<p>English poet and novelist <a href="https://standardebooks.org/ebooks/thomas-hardy">Thomas Hardy</a>, who met Whymper in 1894, was inspired by the 1865 tragedy to write a <a href="https://www.gutenberg.org/files/3168/3168-h/3168-h.htm#page288">sonnet</a>, “Zermatt: To the Matterhorn,” which also touches on this subject. Its main aim may have been, as Eric Christen wrote in <em><a href="https://www.jstor.org/stable/45272596">The Thomas Hardy Journal</a></em>, to describe the “<a href="https://standardebooks.org/ebooks/edward-whymper/scrambles-amongst-the-alps-in-the-years-1860-69/text/endnotes#note-380">fog-bow</a>” Whymper and the Taugwalders saw after their comrades fell, and to juxtapose it with the celestial phenomena that in literature and myth accompany events of great human significance.</p>
		<p>But relevant to “vanity,” the sestet also mentions the “bloody end” of Julius Caesar’s power: even the most impressive might is finite. As Shakespeare’s <a href="https://standardebooks.org/ebooks/william-shakespeare/poetry/text/sonnets#sonnet-60">sonnet LX</a> says of time, “nothing stands but for his scythe to mow.”</p>
		<p>“Zermatt: To the Matterhorn” ends with the global darkness of Good Friday, and Whymper’s outlook in the book seems bleak—but not entirely. Along with the griefs on which he didn’t dare dwell, and the frustrations and annoyances he didn’t hesitate to report, Whymper emphasizes that his attempts on the Matterhorn also brought him “joys too great to be described in words.” And the recollection of these, he says “cannot be effaced.”</p>
		<p>Among those ineffaceable recollections he counted the beauty of the vistas he saw, and the goodwill of those who helped him on his attempts. One of these people, and one of the book’s most memorable characters, was the Breuil peasant and guide Luc Meynet, of whom Whymper made a <a href="https://standardebooks.org/ebooks/edward-whymper/scrambles-amongst-the-alps-in-the-years-1860-69/text/chapter-15#illustration-97">portrait</a>, and first met “carolling, as if this was not a world of woe.”</p>
		<p>Without suggesting that Meynet was at all avian—he’s treated condescendingly enough in the book—this detail brings to mind the main image of another poem by Hardy, “The Darkling Thrush,” in which a bird’s carolling strikes the narrator as incongruent with the desolation of its surroundings.</p>
		<p>“The Darkling Thrush” is often cited as a New Year’s poem, having been written around the end of both a year and a century—though it’s one that, with its outleant corpse and broken lyre-strings, complies well with Whymper’s injunction to “think at the beginning what may be the end.”</p>
		<p>The poem has also been called Hardy’s most allusive poem: the best-known of its allusions is to the “darkling plain” of <a href="https://standardebooks.org/ebooks/matthew-arnold">Matthew Arnold’s</a> “Dover Beach,” the pebbles of which might themselves recall the first line of Shakespeare’s sonnet LX.</p>
		<p><em>Scrambles Amongst the Alps</em> has something of both “darkling thrush” and “darkling plain”: an “eternal note of sadness” following terrible loss, but also real, if fleeting, notes of joy in laboring for, and realizing, a hope widely believed impossible.</p>
		<p>The woe of its best-known story is confounded by lesser-known, brighter elements—even if they’re only “thin atomies” in comparison—praising the worth of the endeavour and the value of the toil it required, despite the cruel hand the explorers were dealt.</p>
		<h2 id="ebooks-in-this-newsletter">Free ebooks in this post</h2>
		<?= Template::EbookCarousel(['carousel' => $carousel]) ?>
	</section>
</main>
<?= Template::Footer() ?>
