<?
$carousel = Ebook::GetAllBySet([877, 144]);
?>
<?= Template::Header(title: 'Number Theory in the First Dramas Since the Fall of Rome', css: ['/css/blog.css']) ?>
<main>
	<section class="narrow blog">
		<nav class="breadcrumbs"><a href="/blog">Blog</a> →</nav>
		<h1>Number Theory in the First Dramas Since the Fall of Rome</h1>
		<p class="byline">By Erin Endrei</p>
		<?= Template::DonationCounter() ?>
		<?= Template::DonationProgress() ?>
		<div class="editors-note">
			<p>This article first appeared in the November 2025 edition of our <a href="/newsletter">email newsletter</a>.</p>
		</div>
		<p>Born around 935, Hrotsvit, or <a href="https://standardebooks.org/ebooks/roswitha-of-gandersheim">Roswitha of Gandersheim</a>, was a secular canoness of Gandersheim Abbey in Lower Saxony, Germany. At the suggestion of her abbess, Hrotsvit first wrote eight religious legends, and later, probably before 965, produced the six comedies for which she is today best remembered. These plays form a Christian response to the six comedies of Terence, which were widely read by the literate in Hrotsvit’s day. In her preface to the reader, Hrotsvit describes her dramatic aims as “being to glorify, within the limits of my poor talent, the laudable chastity of Christian virgins in that selfsame form of composition which has been used to describe the shameless acts of licentious women.”</p>
		<p>Almost a millenium later, in 1923, the playwright and campaigner <a href="https://en.wikipedia.org/wiki/Christabel_Marshall">Christopher St. John</a> translated all six of Hrotsvit’s comedies. Her translation contains a fascinating footnote that illustrates one of the difficulties in appreciating these works.</p>
		<p>One puzzling choice Hrotsvit made when writing was to incorporate what she calls “threads and scraps from the mantle of philosophy.” This reference to the first prose section of Boethius’ <a href="https://standardebooks.org/ebooks/boethius/the-consolation-of-philosophy/h-r-james"><em>Consolation of Philosophy</em></a> occurs in the other document included as a preface to the comedies, Hrotsvit’s notoriously self-deprecating letter to some “learned patrons” of her work. The relevant philosophical “threads and scraps” are found only in her two last dramas, <em>Paphnutius</em> and <em>Sapientia</em>; this is part of the evidence for the <a href="https://archive.org/details/deutschedichterd00wintuoft/page/522/mode/1up?q=Dubletten">theory of the scholar and editor Paul von Winterfeld</a> that they were written later than the first four. According to <a href="https://www.jstor.org/stable/3289343">Cornelia C. Coulter’s 1929 judgement</a>, “these threads only detract from the dramatic value of the plays.” So why did Hrotsvit include them?</p>
		<p>St. John provides one explanation in a footnote attached to a passage in Hrotsvit’s final play. A Christian mother named Sapientia, after whom the play is named, arrives in Rome to evangelize its pagan inhabitants with her daughters Faith, Hope, and Charity. The four are summoned before the emperor Hadrian. When he inquires about the girls’ ages, they encourage their mother to confuse him, which she successfully does, by making her reply in the jargon of medieval number theory.</p>
		<p>Midway through this exchange, St. John <a href="https://standardebooks.org/ebooks/roswitha-of-gandersheim/plays/christopher-st-john/text/endnotes#note-10">explains its inclusion</a>:</p>
		<blockquote>
			<p>It has been my duty to preserve this rather tiresome numerical discourse, which no doubt Roswitha introduced to impress the “learned men” to whom she submitted her work, because it throws an interesting light on the studies pursued in such a monastery as Gandersheim in the 10th century.</p>
		</blockquote>
		<p>By Hrotsvit’s own account, others’ opinions of her work mattered to her; she claims in her letter to her learned patrons that without their encouragement, she would not have had the confidence to go on writing. Still, there is evidence that Sapientia’s mathematical discourse has a more important role in the drama than that of a disconnected display of the dramatist’s education.</p>
		<p>First, it’s another reference to Boethius, whose influence was vast throughout the Middle Ages, and whose importance to Hrotsvit is suggested by its central place in the preface mentioned above. The numerical discourse draws heavily upon Boethius’s <em>De arithmetica</em>, as noted in <a href="https://archive.org/details/hrotsvithaeoper02hrotgoog/page/186/mode/1up?q=pariter">Winterfield’s early edition of her works</a> and more recently by Katharina Wilson, Colleen Richmond, and Caroline Jansen. These scholars argue that the numerical discourse labelled tiresome by St. John has a further allegorical and theological significance: it establishes that the character of Sapientia exemplifies the highest wisdom, which frustrates its enemies in alliance with the three virtues that have arisen from it. God “set everything in number, order, and weight,” Sapientia teaches Hadrian, recounting the Boethian view that the study of numbers is a means of approaching God himself: as Wilson puts it in <a href="https://archive.org/details/hrotsvitofgander0000unse/page/102/mode/2up?q=unravelling">her 1987 study “Mathematical Learning And Structural Composition In The Works Of Hrotsvit,”</a> “man’s ability to understand mathematics ... is his tool for unravelling the patterns of the Divine mysteries.” Hadrian’s ignorance and rejection of mathematics symbolizes, then, his ignorance and rejection of the Christian God whose glorification was Hrotsvit’s stated intention. Scholars have a great deal more to add, but if even just this is right, then the numerical discourse has an important symbolic role in the play.</p>
		<p>The scholarly consensus tends towards preferring the claim of coherence to St. John’s perception of incoherence. In an influential 1984 study, Peter Dronke argues against viewing Hrotsvit’s dramas as mere linguistically substandard Christianizations of Terence. Hrotsvit is “supersubtle,” he claims, and <a href="https://archive.org/details/womenwritersofmi0000dron/page/64/mode/2up?q=boldest">in a frequently cited assessment declares</a> that her subtlety extends to the organization of her works: “In the harmonies of theme and structure that she succeeded in establishing, she achieved the boldest and most elaborate compositional design in Carolingian or Ottonian literature and art, at least as far as the surviving monuments can show." The Boethian “threads and scraps,” of which we have only mentioned one, belong to that design.</p>
		<p>Viewing them as primarily performative is also hard to square with Hrotsvit’s words in the preface to the reader. St. John translates its conclusion:</p>
		<blockquote>
			<p>If this pious devotion gives satisfaction I shall rejoice; if it does not, either on account of my own worthlessness or of the faults of my unpolished style, I shall still be glad that I made the effort.</p>
		</blockquote>
		<p>In the chapter just mentioned, Dronke <a href="https://archive.org/details/womenwritersofmi0000dron/page/68/mode/2up?q=labour">provides an alternative translation</a>:</p>
		<blockquote>
			<p>If my labour of love gives pleasure to anyone, I’ll be glad; but if, because of my worthlessness or the boorishness of my flawed style, it pleases no one, what I have created still gives delight to me[.]</p>
		</blockquote>
		<p>So it’s true that Hrotsvit expresses a general concern with others’ opinions and reactions to her writings; and so the potential effects of her philosophical allusions upon her audience may be worth considering. But modern scholarship suggests that those external effects are no more interesting than the allusions’ internal significance.</p>
		<p>Hrotsvit also, as just quoted, expresses that her work will please her regardless of whether it pleases anybody else. It’s hard to understand how it could please her if not in part due to the cohesion of its elements, its internal coherence, which allusions like the numerical discourse help to establish.</p>
		<p>Some of these allusions may be too medieval for modern readers to appreciate, in either sense of that word. Despite St. John’s important contributions to making Hrotsvit more widely known to Anglophone readers, her footnote concerning Sapientia’s numerical discourse is a case in point.</p>
		<h2 id="ebooks-in-this-newsletter">Free ebooks in this post</h2>
		<?= Template::EbookCarousel(carousel: $carousel) ?>
	</section>
</main>
<?= Template::Footer() ?>
