<?
$carousel = Ebook::GetAllBySet([396, 391, 390]);
?>
<?= Template::Header(title: 'The Orthodoxy of Thursday', css: ['/css/blog.css']) ?>
<main>
	<section class="narrow blog">
		<nav class="breadcrumbs"><a href="/blog">Blog</a> →</nav>
		<h1>The Orthodoxy of Thursday</h1>
		<p class="byline">By Erin Endrei</p>
		<?= Template::DonationCounter() ?>
		<?= Template::DonationProgress() ?>
		<div class="editors-note">
			<p>This article first appeared in the August 2025 edition of our <a href="/newsletter">email newsletter</a>.</p>
		</div>
		<p><a href="/ebooks/g-k-chesterton">G. K. Chesterton’s</a> thirty-fifth year, 1908, was not his most prolific, but it was nevertheless notable. It saw the publication of his most celebrated novel, <i><a href="/ebooks/g-k-chesterton/the-man-who-was-thursday">The Man Who Was Thursday</a></i>, followed by one of his best-known nonfiction works, <i><a href="/ebooks/g-k-chesterton/orthodoxy">Orthodoxy</a></i>.</p>
		<p>These two books are interesting to read together, because apart from any substantial connections or contrasts between them, they also serve as a highly entertaining introduction to Chesterton’s earlier intellectual and literary style, the most salient features of which are its paradoxes and its humor—the first sometimes clearly calculated to produce the second.</p>
		<p>According to the introduction of <i>Orthodoxy</i>, however, Chesterton didn’t see his work as essentially “light,” or as only an exercise in paradox, even if that remains an important part of its reputation today, as it was then. “Mere light sophistry,” he writes, “is the thing that I happen to despise most of all things, and it is perhaps a wholesome fact that this is the thing of which I am generally accused. I know nothing so contemptible as a mere paradox; a mere ingenious defence of the indefensible.” He goes on later in defense of himself: “I never in my life said anything merely because I thought it funny; though, of course, I have had ordinary human vainglory, and may have thought it funny because I had said it.”</p>
		<p><i>Orthodoxy</i> is the sequel to a book called <i><a href="/ebooks/g-k-chesterton/heretics">Heretics</a></i>, which he characterizes as “a series of hasty but sincere papers” in which he contested and criticized the views of many of his literary contemporaries including <a href="/ebooks/rudyard-kipling">Rudyard Kipling</a>, <a href="/ebooks/h-g-wells">H. G. Wells</a>, Lowe Dickinson, and his good friend and foil <a href="/ebooks/george-bernard-shaw">George Bernard Shaw</a>. Critics of <i>Heretics</i>—among them <a href="https://archive.org/details/gkchestertoncrit00ches/page/152/mode/1up?q=heretics">his brother Cecil</a>—had complained that Chesterton was all too willing to denounce others’ views, but had failed to express any “clearly defined doctrines” of his own. In the wake of <i>Heretics</i>, <i>Orthodoxy</i> was intended to remedy that failure.</p>
		<p>The book defends the Christian orthodoxy that Chesterton claimed to have unwittingly reinvented himself, a process he described using the metaphor of an English yachtsman aiming for some undiscovered shore but unwittingly “rediscovering” England itself after a slight navigational miscalculation. While <i>Orthodoxy</i> frequently mentions “the Church,” Chesterton only became a Roman Catholic in 1922; he specifies in the book’s introduction that he means to discuss the orthodoxy expressed in the Apostles’ Creed, and will leave the question of ecclesiastical authority for another book. So the orthodoxy in question is a Christian orthodoxy that was not yet quite Roman in character, but one that would lead its author ultimately in that direction.</p>
		<p>In <i>Orthodoxy</i>, Chesterton defines Christianity as “a superhuman paradox whereby two opposite passions may blaze beside each other.” The two passions he took to constitute this paradox are violence and nonresistance. These appear to be only the concrete expressions of the two more general opposing passions introduced earlier, namely hatred of the world and love of it:</p>
		<blockquote>
			<p>“Can he hate it enough to change it, and yet love it enough to think it worth changing? Can he look up at its colossal good without once feeling acquiescence? Can he look up at its colossal evil without once feeling despair? Can he, in short, be at once not only a pessimist and an optimist, but a fanatical pessimist and a fanatical optimist?”</p>
		</blockquote>
		<p><i>Thursday</i> is the fantastical tale of one man’s fight against what at first is hinted at as being a sort of political fanaticism, but then reveals itself to be something more abstract, namely a general impulse to destroy. The novel begins by introducing two poets, Lucian Gregory and Gabriel Syme, the novel’s protagonist. Their very names have a Christian significance: Lucian brings the spirit of the Luciferian Fall, of <i lang="la">non serviam</i>; Gabriel of the Annunciation, of <i lang="la">lux in tenebris</i>. Gregory reminds us of the Latin for “crowd, horde”; “Syme” perhaps of “simian,” an individual everyman.</p>
		<p>The book follows Syme’s nightmarish adventures as he becomes a secret agent of the police, infiltrating the “Anarchist Council” to which Gregory belongs. Along with a growing band of allies, it’s Syme’s aim to undermine the “anarchists,” a word used interchangeably with “dynamiters,” who want to destroy not merely all law and order, but, essentially, everything. (These anarchists, needless to say, aren’t representative of actual political anarchism, let alone of Christian anarchism.)</p>
		<p><i>Thursday</i> and <i>Orthodoxy</i> were published in the same year. What is the connection between them?</p>
		<p>In Cecil’s <a href="https://archive.org/details/gkchestertoncrit00ches">biography of his brother</a>, he records that he looked forward to the publication of <i>Orthodoxy</i>, because “so far, almost the only exposition we have of Mr. Chesterton’s own system of doctrine is to be found in the wild last chapter of <i>The Man who was Thursday</i>.”</p>
		<p>Eight decades later, another biographer of Chesterton, Alzina Dale, <a href="https://archive.org/details/outlineofsanityb0000dale/page/114/mode/1up?q=Thursday">would write</a> that <i>Thursday</i> consists of a <em>dramatization</em> of the ideas of <i>Orthodoxy</i>. It is, in her view, a novelistic expression of the intellectual struggle described in <i>Orthodoxy</i>, and the safe harbor of sanity and sense that Chesterton wrote of finding in Christian orthodoxy. Dale’s view appears to accord with Cecil’s, who claims also that the book’s last chapter provides “the best expression of the foothold of faith which G. K. C. has found for himself at the last.”</p>
		<p>By contrast, on Wikipedia, one will find a <a href="https://en.wikipedia.org/wiki/The_Man_Who_Was_Thursday#Debate_on_the_novel&#39;s_pessimism">quotation to the contrary</a> from the editor of the <i>New Statesman</i>, John Gray. Gray argued in 2010 that <i>Thursday</i> reveals a vision against which <i>Orthodoxy</i> and the rest of Chesterton’s later work, was directed. In Gray’s view, <i>Thursday</i> reveals a terrifying vision of chaos that Chesterton strove to forget, not a vision to which he had formulated a response, whether in <i>Orthodoxy</i> or later works.</p>
		<p>While I believe that there’s a good argument against Gray’s interpretation, there isn’t space to make it here. Instead I want to indicate one other lesser-known ground in support of Dale’s opinion: at crucial junctures in both books, Chesterton describes what he hears a “voice” telling him, or what he inexplicably feels is being not argued rationally <em>at</em> him, but impressed viscerally <em>upon</em> him by some supernatural presence.</p>
		<p>In <i>Thursday</i> it happens just once, at the very crux of the book, after Syme has made a speech in which he declares his answer to the problem of evil. The vital missing premise that seals the theodicy, and ends the scene, is the <em>voice</em> that Syme hears quoting a question of Jesus’ in the New Testament. It’s this that provides what Cecil called Chesterton’s “foothold of faith.”</p>
		<p>In <i>Orthodoxy</i>, too, an otherworldly voice appears at important moments. This begins at the end of the fourth chapter, where he describes what he <em>feels</em> “in his bones,” “ultimate attitudes towards life; the soils for the seeds of doctrine,” which “in some dark way I thought before I could write, and felt before I could think.”</p>
		<p>Later, in the seventh chapter, Chesterton refers back to these inexplicable, apparently otherwordly perceptions (emphasis added):</p>
		<blockquote>
			<p>“When I had written this down, I <em>felt once again the presence</em> of something else in the discussion: as a man hears a church bell above the sound of the street. <em>Something seemed to be saying</em>, ‘My ideal at least is fixed; for it was fixed before the foundations of the world. My vision of perfection assuredly cannot be altered; for it is called Eden.’</p>
		</blockquote>
		<p>Later:</p>
		<blockquote>
			<p>“Here again my contemplation was cloven by <em>the ancient voice</em> which said, ‘I could have told you all this a long time ago.’”</p>
		</blockquote>
		<p>Later again:</p>
		<blockquote>
			<p>“But again <em>I seem to hear</em>, like a kind of echo, an answer from beyond the world.”</p>
		</blockquote>
		<p>This otherworldly voice is, I suggest, the same one that he has his protagonist Syme hear in <i>Thursday</i>. It’s evidently Chesterton’s expression of the voice of God, of revelation, and therefore for its author a gleam of hope—or rather, <em>the</em> gleam of hope to which he refers in a <a href="https://archive.org/details/illustrated-london-news-1930-1939/1930-1939/1936/Illustrated%20London%20News%20%235069v188%20%281936-06-13%29%20%28BNA%29/page/1042/mode/1up">much-quoted article from the <i>London Illustrated</i></a> published a day before his death.</p>
		<p>Of each book’s many interacting elements, this is just one, and quite a small one at that. Still, it’s a connection that lends some legitimacy to reading the ending of <i>Thursday</i> in light of the autobiographical story of <i>Orthodoxy</i>, and to better understand the former as a kind of allegory.</p>
		<h2 id="ebooks-in-this-newsletter">Free ebooks in this post</h2>
		<?= Template::EbookCarousel(carousel: $carousel) ?>
	</section>
</main>
<?= Template::Footer() ?>
