<?
$carousel = Ebook::GetAllBySet([698, 142, 389]);
?>
<?= Template::Header(title: 'The Book That Solved Philosophy', css: ['/css/blog.css']) ?>
<main>
	<section class="narrow blog">
		<nav class="breadcrumbs"><a href="/blog">Blog</a> →</nav>
		<h1>The Book That Solved Philosophy</h1>
		<p class="byline">By Erin Endrei</p>
		<?= Template::DonationCounter() ?>
		<?= Template::DonationProgress() ?>
		<div class="editors-note">
			<p>This article first appeared in the June 2026 edition of our <a href="/newsletter">email newsletter</a>.</p>
		</div>
		<p><a href="https://standardebooks.org/ebooks/ludwig-wittgenstein">Ludwig Wittgenstein</a>, born in 1889, was a member of one of the most prominent families of late nineteenth-century Vienna. After studying engineering, he went on to exert an enormous influence upon English-speaking philosophy in the first half of the twentieth century.</p>
		<p>The <i><a href="https://standardebooks.org/ebooks/ludwig-wittgenstein/tractatus-logico-philosophicus/c-k-ogden">Tractatus Logico-Philosophicus</a></i> was the only philosophical work he published during his lifetime, and despite its brevity it has earned a well-deserved reputation for obscurity. It primarily concerns the relationship between language and the world, but also responds to then-recent advances in logic made by the German mathematician Gottlob Frege and the English philosopher <a href="https://standardebooks.org/ebooks/bertrand-russell">Bertrand Russell</a>.</p>
		<p>Wittgenstein took a hiatus from research in aeronautical engineering in October 1911 in order to travel to Cambridge to study with Russell. This had been the recommendation of Frege, whom Wittgenstein had visited earlier that year after becoming captivated by logic and the foundations of mathematics.</p>
		<p>In 1913 Wittgenstein spent time in Norway working on logic. While mostly alone, he did accept visitors, among them the Cambridge philosopher and author of <a href="https://standardebooks.org/ebooks/g-e-moore/principia-ethica"><i>Principia Ethica</i></a>, <a href="https://standardebooks.org/ebooks/g-e-moore">G. E. Moore</a>, to whom Wittgenstein dictated some notes. In 1915, while a volunteer in the Austro-Hungarian army, he began transforming his notes on logic into the treatise published in German as <i>Logisch-Philosophische Abhandlung</i> and in English as <i>Tractatus Logico-Philosophicus</i>, a title suggested by Moore as a reference to Spinoza’s <i>Tractatus Theologico-Politicus</i>.</p>
		<p>Wittgenstein was determined to find a publisher but struggled to do so. The <i>Tractatus</i> would eventually first appear in English in 1922, in an English-German parallel text edition translated by Frank Ramsey (even though Ramsey's publisher, C. K. Ogden, took credit), and with an introduction by Russell. Despite the translation’s reputation for awkward literalness, it’s of considerable historical importance, as Wittgenstein himself read and corrected it, <a href="https://archive.org/details/letterstockogden0000witt/mode/1up">sending his comments</a> and suggestions to Ogden.</p>
		<p>Wittgenstein would later turn away from some of the main conceptions of the <i>Tractatus</i>, but <a href="https://archive.org/details/letterstorussell00witt_0/page/70/mode/1up?q=%22life%27s+work%22">in a letter</a> to Russell from 12 June 1919, referred to it as his life’s work.</p>
		<p>Because of Russell’s reputation in England, and Wittgenstein’s lack of one, the former’s introduction to the <i>Tractatus</i> was instrumental in securing the book’s publication. Wittgenstein, however, was unhappy with Russell’s summary.</p>
		<p>It wasn’t the first time he’d felt his ideas to have been misunderstood by his former mentor: discussing the manuscript of the <i>Tractatus</i> that he had had sent to Russell, he took the opportunity to <a href="https://archive.org/details/letterstorussell00witt_0/page/71/mode/1up">restate its main point in another letter to Russell</a>:</p>
		<blockquote>
			<p>Now I’m afraid you haven’t really got hold of my main contention, to which the whole business of logical prop[osition]s is only a corollary. The main point is the theory of what can be expressed (<i>gesagt</i>) by prop[osition]s—i.e. by language—(and, which comes to the same, what can be <em>thought</em>) and what can not be expressed by prop[osition]s, but only shown (<i>gezeigt</i>); which, I believe, is the cardinal problem of philosophy.</p>
		</blockquote>
		<p>The preface of the <i>Tractatus</i> makes clear, further, that he didn’t take the book only to <em>discuss</em> the cardinal problem of philosophy; he took it to <em>solve</em> that problem, as it had solved <em>all</em> philosophical problems. The truth of its thoughts seemed to him, the preface records, “unassailable and definitive.”</p>
		<p>This has been viewed as hard to square with the penultimate proposition of the book, which famously compares its numbered propositions to the steps of a ladder that must be thrown away after being used to ascend to the correct view of things.</p>
		<p>There are competing ways of understanding this apparent paradox, and considerable scholarly debate about it. Instead of pursuing that debate, we’ll briefly discuss something else: that the “main contention” quoted in the letter above is closely connected with the conception of philosophy that is described in the book. This conception stands in contrast to one advanced in a popular work by Russell published the year after his first meeting with Wittgenstein.</p>
		<p>As Wittgenstein wrote in the above letter, the main point of the <i>Tractatus</i> concerns the boundary between what can be <em>said</em> and what can only be <em>shown</em>. This boundary relates to the nature of philosophy itself: according to <a href="https://standardebooks.org/ebooks/ludwig-wittgenstein/tractatus-logico-philosophicus/c-k-ogden/text/tractatus-logico-philosophicus#section-6.53">proposition 6.53</a>, the right method of philosophy would consist of informing people when they fail to respect that boundary, i.e., attempting to say the unsayable. Philosophy’s goal is to clarify (sayable) propositions and delimit what is sayable from within, not to create new objects of knowledge in the form of “philosophical propositions.”</p>
		<p>Russell certainly considered the clarification of propositions to be one of the discipline’s distinctive functions, one that Frege’s development of predicate logic had been crucial in furthering: it’s Russell’s analysis of definite descriptions that is referred to in <a href="https://standardebooks.org/ebooks/ludwig-wittgenstein/tractatus-logico-philosophicus/c-k-ogden/text/tractatus-logico-philosophicus#section-4.0031">proposition 4.0031</a>. And as in <a href="https://standardebooks.org/ebooks/ludwig-wittgenstein/tractatus-logico-philosophicus/c-k-ogden/text/tractatus-logico-philosophicus#section-4.112">proposition 4.112</a>, Russell, in his general-interest book <a href="https://standardebooks.org/ebooks/bertrand-russell/the-problems-of-philosophy"><i>The Problems of Philosophy</i></a>, holds that philosophy is an activity rather than a body of doctrine.</p>
		<p>But according to the account in <i>The Problems of Philosophy</i>, that activity is primarily the pursuit of knowledge, not only of maximal clarity. Philosophy aims to do more than just elucidate what has already been said; like natural science, it might also establish new truths.</p>
		<p>This, Russell admits, philosophy may seem unlikely ever to do, given its track record in avoiding contention; but that improbability does not stop knowledge from being its aim. But its value doesn’t depend on meeting that aim; rather, its value lies in its very uncertainty, and hence in its corrosive effect upon dogmatism: in its questions, not its answers.</p>
		<p>Neither the value nor the aim of philosophy is taken by Russell to involve any notion of things unsayable or inexpressible.</p>
		<p>What the inexpressible is in Wittgenstein’s <i>Tractatus</i> is something we don’t have space to properly address, and probably wouldn’t, anyway, succeed in correctly saying. It includes the sense of the propositions of logic, like the law of excluded middle; but also propositions of ethics, the consignment of which to unsayability understandably caused Russell “intellectual discomfort,” as his introduction records.</p>
		<p>This is not to say that ethics is as irrelevant to the <i>Tractatus</i> as it is to Russell and Whitehead’s mathematical magnum opus, <i>Principia Mathematica</i>. On the contrary, in a <a href="https://archive.org/details/wittgensteinsvie00jani/page/192/mode/1up?q=%22ethical+one%22">much-quoted letter</a>, Wittgenstein wrote to the publisher Ludwig von Ficker of his belief that the point of the <i>Tractatus</i> was an ethical one, and that the most important part of it was what it refrained from saying.</p>
		<p>This last claim has helped to ensure enduring interest in the <i>Tractatus</i> despite the obscurity of what it does say, which was unclear even to the period’s greatest logicians, Frege and Russell. But the beginning of the letter first quoted above reminds us that it wasn’t so easy, either, on its author:</p>
		<blockquote>
			<p>[S]ome of your questions want a very lengthy answer and you know how difficult it is for me to write on logic. That’s also the reason why my book is so short, and consequently so obscure. But that I can’t help.</p>
		</blockquote>
		<h2 id="ebooks-in-this-newsletter">Free ebooks in this post</h2>
		<?= Template::EbookCarousel(carousel: $carousel) ?>
	</section>
</main>
<?= Template::Footer() ?>
