<?
$carousel = Ebook::GetAllBySet([952, 601]);
?>
<?= Template::Header(title: 'The Bridges of San Luis Rey', css: ['/css/blog.css']) ?>
<main>
	<section class="narrow blog">
		<nav class="breadcrumbs"><a href="/blog">Blog</a> →</nav>
		<h1>The Bridges of San Luis Rey</h1>
		<p class="byline">By Erin Endrei</p>
		<?= Template::DonationCounter() ?>
		<?= Template::DonationProgress() ?>
		<div class="editors-note">
			<p>This article first appeared in the October 2025 edition of our <a href="/newsletter">email newsletter</a>.</p>
		</div>
		<p>Thornton Wilder’s 1927 novel <i><a href="/ebooks/thornton-wilder/the-bridge-of-san-luis-rey">The Bridge of San Luis Rey</a></i> recounts a Franciscan friar’s attempt to find divine intention in what appears to be a tragic accident. At midday on Friday the twentieth of July, 1714, three parties of travellers, five people in total, fall to their deaths while crossing a rope bridge somewhere between the cities of Lima and Cuzco in Peru. Brother Juniper witnesses the collapse and works for six years thereafter on a book whose purpose is to explain why those particular people were chosen by God to die in that particular place, time, and manner. The book will thereby “justify the ways of God to man,” as Wilder <a href="/ebooks/john-milton/paradise-lost/text/book-1#:~:text=justify%20the%20ways%20of%20God%20to%20men.">quotes</a>, and finally fulfil Brother Juniper’s long-held aspiration of proving theology to be an exact science.</p>
		<p>The novel was an instant bestseller and lucrative for Wilder; it went on to win the 1928 Pulitzer Prize. It’s consistently funny in its use of understatement, but is also a subtler work than it might first appear. Sometimes labelled sentimental, it was intended to be “charmingly ironic,” according to a letter by Wilder; the pathos of <i>The Bridge</i> was supposed to “lie suspended in its irony.” Another aspect of the novel, its basic structure, also weakens the idea that it offers only sentimentality rather than literary value. It’s its structure, and what it might reveal about the book’s central question, that we’ll consider here.</p>
		<p>To discuss the book’s structure is not necessarily to move away from its central symbol, the bridge. There are at least two, and perhaps even three, bridges discernible in the text: three possible meanings of the common noun in the title. The first is the straightforward one, the fictional rope bridge whose collapse in the novel’s first sentence provides Brother Juniper with the “perfect laboratory” for scientific investigations of divine intention. The second is the notion described in the novel’s final sentence, which is eminiently quotable and which we won’t ruin for the reader. The third possible bridge is the book’s structure itself, which we’ll focus on not least because it’s more an aid to understanding than a spoiler.</p>
		<p>The sort of structure I mean can be found in the book’s table of contents. It consists of five chapters, beginning with “Perhaps an Accident” and ending with “Perhaps an Intention,” which are the only chapters that fully concern Brother Juniper. “Perhaps an Accident” introduces him and his project; the second chapter mentions him only in its first sentence, and only to dismiss his knowledge of that chapter’s subject. Brother Juniper does not otherwise appear in the middle three chapters, so those three chapters may seem to form a bridge between the first and last—from “Perhaps an Accident” to “Perhaps an Intention,” from the introduction of Brother Juniper’s project to its ultimate fate (and his). That is, the book’s structure <em>itself</em> is that of a bridge.</p>
		<p>If that’s right, then the structure itself expresses the central concern of Brother Juniper, and of the book: how to bridge the gap from “perhaps an accident” to “perhaps an intention”? How can an argument from observed order to design be made in the absence of the alleged designer?</p>
		<p>Juniper, according to the narrator, never manages it; when he tries (tragicomically) to do it by quantifying the worth of different victims of a plague, his tables lead him to disquieting conclusions, and he ends by casting his work into the sea. The narrator drily concludes: “The discrepancy between faith and the facts is greater than is generally assumed.” Brother Juniper fails to explain away that discrepancy; it’s a basic question of interpretation whether or not the book takes itself to succeed. Does the bridge-like structure of the novel tell us that Wilder affirms the possibility of bridging the gap between accident and intention?</p>
		<p>The center of the book might provide a hint. The middle of the middle three chapters, “Estaban,” is literally the novel’s central chapter, but could also be understood as its thematic centrepiece. Whether or not that’s so, it matters visually that the chapter is central and that its title consists of only one name, while those surrounding it have two; for this has the consequence that turned on its side, the Table of Contents looks not just like a bridge but a sagging one, with two poles or ends (the “Perhaps” chapters) and two sets of two names surrounding the lone “Estaban,” the point of collapse.</p>
		<p>If the structure of the book is that of a collapsing bridge, it shouldn’t be expected to take us from (fictional) facts to faith, to construct a safe argumentative path from accident to intention. This is in keeping with the ambivalent words of the narrator that conclude the first chapter, and with Wilder’s <a href="https://archive.org/details/conversationswit0000unse_o3u3/page/58/mode/2up">statement in 1953</a> that he took the novel to have posed the question of divine intention, but to have left it unanswered; the important thing was to ask the question correctly. The novel may be consistent with Juniper’s faith but was not intended to be a profession of it.</p>
		<p>It’s no mystery why the book became popular. In spite of the narrator’s self-declared fallibility, the reading public surely judged that he was correct about the “spring” that was the central passion of each characters’ life, and correct about the primacy of the “bridge” mentioned in the work’s final sentence. Most readers will easily assent to this primacy even as they remain ambivalent about, or outright dismissive of, the possibility Wilder subtly gestures at, just once: “the spring within the spring.”</p>
		<p>A skeptic, like the university student mentioned in the book’s final chapter, would deny that Wilder’s narrator “missed” the very spring within the spring, on the grounds that there <em>is</em> no spring to miss. Similarly, some might question the perception of the chapter structure put forward here, and contend that there is no third bridge within <i>The Bridge</i>, that the structure of the novel was not intended to be bridge-like; if it looks vaguely that way, then that could just as easily have been an accident. The skeptical view is possible; to suggest it brings the novel’s central question down to earth.</p>
		<h2 id="ebooks-in-this-newsletter">Free ebooks in this post</h2>
		<?= Template::EbookCarousel(carousel: $carousel) ?>
	</section>
</main>
<?= Template::Footer() ?>
