CREATE TABLE `Artists` (
  `ArtistId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Name` varchar(191) NOT NULL,
  `UrlName` varchar(255) NOT NULL,
  `DeathYear` smallint unsigned NULL,
  PRIMARY KEY (`ArtistId`),
  UNIQUE KEY `idxUnique` (`Name`,`DeathYear`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Artists (Name, UrlName, DeathYear)
VALUES
('Aaron Douglas', 'aaron-douglas', 1979),
('Abanindranath Tagore', 'abanindranath-tagore', 1951),
('Abbott Handerson Thayer', 'abbott-handerson-thayer', 1921),
('Abraham Manievich', 'abraham-manievich', 1942),
('Abraham Walkowitz', 'abraham-walkowitz', 1965),
('Adolph Menzel', 'adolph-menzel', 1905),
('Adrien Dauzats', 'adrien-dauzats', 1868),
('Aert van der Neer', 'aert-van-der-neer', 1677),
('Akseli Gallen-Kallela', 'akseli-gallen-kallela', 1931),
('Albert Beck Wenzell', 'albert-beck-wenzell', 1917),
('Albert Bierstadt', 'albert-bierstadt', 1902),
('Albert Bloch', 'albert-bloch', 1961),
('Albert Edelfelt', 'albert-edelfelt', 1905),
('Albert Gleizes', 'albert-gleizes', 1953),
('Albert Pinkham Ryder', 'albert-pinkham-ryder', 1917),
('Alberto Pasini', 'alberto-pasini', 1899),
('Albertus Verhoesen', 'albertus-verhoesen', 1881),
('Alexander Helwig Wyant', 'alexander-helwig-wyant', 1892),
('Alexander Joseph Daiwaille', 'alexander-joseph-daiwaille', 1888),
('Alexander von Wagner', 'alexander-von-wagner', 1919),
('Alexandre Calame', 'alexandre-calame', 1864),
('Alexandre Jacovleff', 'alexandre-jacovleff', 1938),
('Alexandre-François Desportes', 'alexandre-francois-desportes', 1743),
('Alfred Agache ', 'alfred-agache', 1915),
('Alfred de Dreux', 'alfred-de-dreux', 1860),
('Alfred Kappes', 'alfred-kappes', 1894),
('Alfred Kowalski', 'alfred-kowalski', 1915),
('Alfred Munnings', 'alfred-munnings', 1959),
('Alfred Philippe Roll', 'alfred-philippe-roll', 1919),
('Alfred Stevens', 'alfred-stevens', 1906),
('Alice Pike Barney', 'alice-pike-barney', 1931),
('Alphonse Legros', 'alphonse-legros', 1911),
('Alphonse Mucha', 'alphonse-mucha', 1939),
('Alphonse-Marie-Adolphe de Neuville', 'alphonse-marie-adolphe-de-neuville', 1885),
('Alson Skinner Clark', 'alson-skinner-clark', 1949),
('Amadeo de Souza Cardoso', 'amadeo-de-souza-cardoso', 1918),
('Ambrose McEvoy', 'ambrose-mcevoy', 1927),
('Anders Zorn', 'anders-zorn', 1920),
('Andrea Appiani', 'andrea-appiani', 1817),
('Andrée Rexroth', 'andree-rexroth', 1940),
('Andrew John Henry Way', 'andrew-john-henry-way', 1888),
('Andrew W. Warren', 'andrew-w-warren', 1873),
('Andrzej Bronisław Grabowski', 'andrzej-bronislaw-grabowski', 1886),
('Angel De Cora', 'angel-de-cora', 1919),
('Anne Goldthwaite', 'anne-goldthwaite', 1944),
('Anne-Louis Girodet-Trioson', 'anne-louis-girodet-trioson', 1824),
('Anthony Oberman', 'anthony-oberman', 1845),
('Anthony van Dyck', 'anthony-van-dyck', 1641),
('Anton Mauve', 'anton-mauve', 1888),
('Antonio Zeno Shindler', 'antonio-zeno-shindler', 1899),
('Antti Favén', 'antti-faven', 1948),
('Arkhip Kuindzhi', 'arkhip-kuindzhi', 1910),
('Arnold Böcklin', 'arnold-bocklin', 1901),
('Artemisia Gentileschi', 'artemisia-gentileschi', 1653),
('Arthur Fitzwilliam Tait', 'arthur-fitzwilliam-tait', 1905),
('Arthur Hacker', 'arthur-hacker', 1919),
('Arthur Streeton', 'arthur-streeton', 1943),
('Asher Brown Durand', 'asher-brown-durand', 1886),
('August Heinrich', 'august-heinrich', 1822),
('August Strindberg', 'august-strindberg', 1912),
('Augustus Leopold Egg', 'augustus-leopold-egg', 1863),
('Benjamin West', 'benjamin-west', 1820),
('Benjamin Williams Leader', 'benjamin-williams-leader', 1923),
('Berndt Lindholm', 'berndt-lindholm', 1914),
('Berthe Morisot', 'berthe-morisot', 1895),
('Boris Grigoriev', 'boris-grigoriev', 1939),
('Boris Kustodiev', 'boris-kustodiev', 1927),
('Briton Riviére', 'briton-riviere', 1920),
('Bruno Liljefors', 'bruno-liljefors', 1939),
('Camille Pissarro', 'camille-pissarro', 1903),
('Canaletto', 'canaletto', 1768),
('Carducius Plantagenet Ream', 'carducius-plantagenet-ream', 1917),
('Carl Gustav Carus', 'carl-gustav-carus', 1869),
('Carl Larsson', 'carl-larsson', 1919),
('Carl Redin', 'carl-redin', 1944),
('Carl Spitzweg', 'carl-spitzweg', 1885),
('Carlo Carrà', 'carlo-carra', 1966),
('Carolus-Duran', 'carolus-duran', 1917),
('Caspar David Friedrich', 'caspar-david-friedrich', 1840),
('Cecilia Beaux', 'cecilia-beaux', 1942),
('Charles August Buchel', 'charles-august-buchel', 1950),
('Charles Auguste Émile Durand', 'charles-auguste-emile-durand', 1917),
('Charles Bargue', 'charles-bargue', 1883),
('Charles Bosseron Chambers', 'charles-bosseron-chambers', 1964),
('Charles Caleb Ward', 'charles-caleb-ward', 1896),
('Charles Courtney Curran', 'charles-courtney-curran', 1942),
('Charles Ginner', 'charles-ginner', 1952),
('Charles Haslewood Shannon', 'charles-haslewood-shannon', 1937),
('Charles Marion Russell', 'charles-marion-russell', 1926),
('Charles Mellin', 'charles-mellin', 1649),
('Charles Piazzi Smyth', 'charles-piazzi-smyth', 1900),
('Charles R. Knight', 'charles-r-knight', 1953),
('Charles Robert Leslie', 'charles-robert-leslie', 1859),
('Charles Sprague Pearce', 'charles-sprague-pearce', 1914),
('Charles Thomas Burt', 'charles-thomas-burt', 1902),
('Charles-Émile Jacque', 'charles-emile-jacque', 1894),
('Childe Hassam', 'childe-hassam', 1935),
('Christian Krohg', 'christian-krohg', 1925),
('Christopher R. W. Nevinson', 'christopher-r-w-nevinson', 1946),
('Clarence Gagnon', 'clarence-gagnon', 1942),
('Claude Lorrain', 'claude-lorrain', 1682),
('Claude Monet', 'claude-monet', 1926),
('Colin Campbell Cooper', 'colin-campbell-cooper', 1937),
('Constant Mayer', 'constant-mayer', 1911),
('Constantin Meunier', 'constantin-meunier', 1905),
('Corrado Giaquinto', 'corrado-giaquinto', 1766),
('Cuthbert Edmund Swan', 'cuthbert-edmund-swan', 1931),
('Cyrus Cuneo', 'cyrus-cuneo', 1916),
('Dante Gabriel Rossetti', 'dante-gabriel-rossetti', 1882),
('David Martin', 'david-martin', 1797),
('Diego Velázquez', 'diego-velazquez', 1660),
('Dorothy Stanley', 'dorothy-stanley', 1926),
('Douglas Strachan', 'douglas-strachan', 1950),
('Douglas Volk', 'douglas-volk', 1935),
('E. Borough Johnson', 'e-borough-johnson', 1949),
('Eastman Johnson', 'eastman-johnson', 1906),
('Edgar Degas', 'edgar-degas', 1917),
('Edmund Blair Leighton', 'edmund-blair-leighton', 1922),
('Edmund C. Tarbell', 'edmund-c-tarbell', 1938),
('Edmund Dulac', 'edmund-dulac', 1953),
('Édouard Manet', 'edouard-manet', 1883),
('Édouard Odier', 'edouard-odier', 1887),
('Eduard von Grützner', 'eduard-von-grutzner', 1925),
('Edvard Munch', 'edvard-munch', 1944),
('Edward Bruce', 'edward-bruce', 1943),
('Edward Coley Burne-Jones', 'edward-coley-burne-jones', 1898),
('Edward Poynter', 'edward-poynter', 1919),
('Edward Lamson Henry', 'edward-lamson-henry', 1919),
('Edward Mitchell Bannister', 'edward-mitchell-bannister', 1901),
('Edward Robert Hughes', 'edward-robert-hughes', 1914),
('Edward Wadsworth', 'edward-wadsworth', 1949),
('Edwin Austin Abbey', 'edwin-austin-abbey', 1911),
('Edwin Edwards', 'edwin-edwards', 1879),
('Edwin Landseer', 'edwin-landseer', 1873),
('Edwin Lord Weeks', 'edwin-lord-weeks', 1903),
('Eilif Peterssen', 'eilif-peterssen', 1928),
('El Greco', 'el-greco', 1614),
('Eleanor Fortescue-Brickdale', 'eleanor-fortescue-brickdale', 1945),
('Elihu Vedder', 'elihu-vedder', 1923),
('Elioth Gruner', 'elioth-gruner', 1939),
('Élisabeth Vigée Le Brun', 'elisabeth-vigee-le-brun', 1842),
('Emanuel Gottlieb Leutze', 'emanuel-gottlieb-leutze', 1868),
('Emil Carlsen', 'emil-carlsen', 1932),
('Emile Claus', 'emile-claus', 1924),
('Ernest Hébert', 'ernest-hebert', 1908),
('Ernest Meissonier', 'ernest-meissonier', 1891),
('Ernest William Haslehust', 'ernest-william-haslehust', 1949),
('Ernst Josephson', 'ernst-josephson', 1906),
('Ethel Franklin Betts', 'ethel-franklin-betts', 1959),
('Eugène Boudin', 'eugene-boudin', 1898),
('Eugène Delacroix', 'eugene-delacroix', 1863),
('Eugenio Lucas Villamil', 'eugenio-lucas-villamil', 1918),
('Evelyn De Morgan', 'evelyn-de-morgan', 1919),
('Fedor Encke', 'fedor-encke', 1926),
('Félix Ziem', 'felix-ziem', 1911),
('Félix-Joseph Barrias', 'felix-joseph-barrias', 1907),
('Ferdinand Georg Waldmüller', 'ferdinand-georg-waldmuller', 1865),
('Ferdinand Hodler', 'ferdinand-hodler', 1918),
('Ferdinand Keller', 'ferdinand-keller', 1922),
('Ferdinand von Wright', 'ferdinand-von-wright', 1906),
('Fernand Cormon', 'fernand-cormon', 1924),
('Fernand Khnopff', 'fernand-khnopff', 1921),
('Florence Carlyle', 'florence-carlyle', 1923),
('Floris Claesz. van Dijck', 'floris-claesz-van-dijck', 1651),
('Francesco Furini', 'francesco-furini', 1646),
('Francesco Hayez', 'francesco-hayez', 1882),
('Francis Picabia', 'francis-picabia', 1953),
('Francis Wheatley', 'francis-wheatley', 1801),
('Francisco de Zurbarán', 'francisco-de-zurbaran', 1664),
('Francisco Goya', 'francisco-goya', 1828),
('François Boucher', 'francois-boucher', 1770),
('François Gérard', 'francois-gerard', 1837),
('François-Louis Dejuinne', 'francois-louis-dejuinne', 1844),
('Frank Duveneck', 'frank-duveneck', 1919),
('Frank Edwin Scott', 'frank-edwin-scott', 1929),
('Frank Schoonover', 'frank-schoonover', 1972),
('Frans Hals', 'frans-hals', 1666),
('Frans Snyders', 'frans-snyders', 1657),
('Frans van der Mijn', 'frans-van-der-mijn', 1783),
('Franz Marc', 'franz-marc', 1916),
('Fred Leist', 'fred-leist', 1945),
('Frédéric Bazille', 'frederic-bazille', 1870),
('Frederic Edwin Church', 'frederic-edwin-church', 1900),
('Frederic Leighton', 'frederic-leighton', 1896),
('Frédéric Montenard', 'frederic-montenard', 1926),
('Frederick Carl Frieseke', 'frederick-carl-frieseke', 1939),
('Frederick Goodall', 'frederick-goodall', 1904),
('Frederick McCubbin', 'frederick-mccubbin', 1917),
('Gaines Ruger Donoho', 'gaines-ruger-donoho', 1916),
('Gari Melchers', 'gari-melchers', 1932),
('Georg Friedrich Kersting', 'georg-friedrich-kersting', 1847),
('George Barret', 'george-barret', 1784),
('George Bellows', 'george-bellows', 1925),
('George Catlin', 'george-catlin', 1872),
('George Clausen', 'george-clausen', 1944),
('George Frederic Watts', 'george-frederic-watts', 1904),
('George Grosz', 'george-grosz', 1959),
('George Hall Neale', 'george-hall-neale', 1940),
('George Hayter', 'george-hayter', 1871),
('George Inness', 'george-inness', 1894),
('George Luks', 'george-luks', 1933),
('George Morland', 'george-morland', 1804),
('Georges Braque', 'georges-braque', 1963),
('Georges de La Tour', 'georges-de-la-tour', 1652),
('Georges Michel', 'georges-michel', 1843),
('Georges Seurat', 'georges-seurat', 1891),
('Georges-Victor Hugo', 'georges-victor-hugo', 1925),
('Gerard ter Borch', 'gerard-ter-borch', 1681),
('Gilbert Gaul', 'gilbert-gaul', 1919),
('Giorgione', 'giorgione', 1510),
('Giovanni Battista Tiepolo', 'giovanni-battista-tiepolo', 1770),
('Giovanni Boldini', 'giovanni-boldini', 1931),
('Giovanni Segantini', 'giovanni-segantini', 1899),
('Giuseppe Arcimboldo', 'giuseppe-arcimboldo', 1593),
('Giuseppe De Nittis', 'giuseppe-de-nittis', 1884),
('Glyn Philpot', 'glyn-philpot', 1937),
('Godfried Schalcken', 'godfried-schalcken', 1706),
('Gottfried Franz', 'gottfried-franz', 1905),
('Guillaume Guillon Lethière', 'guillaume-guillon-lethiere', 1832),
('Gustav Klimt', 'gustav-klimt', 1918),
('Gustave Achille Guillaumet', 'gustave-achille-guillaumet', 1887),
('Gustave Caillebotte', 'gustave-caillebotte', 1894),
('Gustave Courbet', 'gustave-courbet', 1877),
('Gyula Benczúr', 'gyula-benczur', 1920),
('H. Lyman Saÿen', 'h-lyman-sayen', 1918),
('Hanna Hirsch-Pauli', 'hanna-hirsch-pauli', 1940),
('Hans Bollongier', 'hans-bollongier', 1645),
('Hans Holbein the Younger', 'hans-holbein-the-younger', 1543),
('Hans Thoma', 'hans-thoma', 1924),
('Hans von Marées', 'hans-von-marees', 1887),
('Harold Mathews Brett', 'harold-mathews-brett', 1955),
('Helen Allingham', 'helen-allingham', 1926),
('Helene Schjerfbeck', 'helene-schjerfbeck', 1946),
('Hendrick ter Brugghen', 'hendrick-ter-brugghen', 1629),
('Hendrik Willem Mesdag', 'hendrik-willem-mesdag', 1915),
('Henri Fantin-Latour', 'henri-fantin-latour', 1904),
('Henri Gervex', 'henri-gervex', 1929),
('Henri Martin', 'henri-martin', 1943),
('Henri Rousseau', 'henri-rousseau', 1910),
('Henry Alexander', 'henry-alexander', 1894),
('Henry Fuseli', 'henry-fuseli', 1825),
('Henry Ossawa Tanner', 'henry-ossawa-tanner', 1937),
('Henry Stacy-Marks', 'henry-stacy-marks', 1898),
('Henry Treffry Dunn', 'henry-treffry-dunn', 1899),
('Henry Ward Ranger', 'henry-ward-ranger', 1916),
('Henryk Siemiradzki', 'henryk-siemiradzki', 1902),
('Herbert James Draper', 'herbert-james-draper', 1920),
('Hieronymus Bosch', 'hieronymus-bosch', 1516),
('Hippolyte Lecomte', 'hippolyte-lecomte', 1857),
('Honoré Daumier', 'honore-daumier', 1879),
('Horatio C. Forjohn', 'horatio-c-forjohn', 1943),
('Howard Chandler Christy', 'howard-chandler-christy', 1952),
('Howard Cushing', 'howard-cushing', 1916),
('Howard Pyle', 'howard-pyle', 1911),
('Hubert Robert', 'hubert-robert', 1808),
('Hubert von Herkomer', 'hubert-von-herkomer', 1914),
('Hugues Merle', 'hugues-merle', 1881),
('Ignacio Zuloaga', 'ignacio-zuloaga', 1945),
('Ilya Repin', 'ilya-repin', 1930),
('Isaac Ilyich Levitan', 'isaac-ilyich-levitan', 1900),
('Isaac Israëls', 'isaac-israels', 1934),
('Ivan Shishkin', 'ivan-shishkin', 1898),
('J. Allen St. John', 'j-allen-st-john', 1957),
('J. C. Leyendecker', 'j-c-leyendecker', 1951),
('J. E. H. MacDonald', 'j-e-h-macdonald', 1932),
('J. M. W. Turner', 'j-m-w-turner', 1851),
('Jacek Malczewski', 'jacek-malczewski', 1929),
('Jacob Appel', 'jacob-appel', 1751),
('Jacob Maris', 'jacob-maris', 1899),
('Jacob van Campen', 'jacob-van-campen', 1657),
('Jacob van Ruisdael', 'jacob-van-ruisdael', 1682),
('Jacoba van Heemskerck', 'jacoba-van-heemskerck', 1923),
('Jacques-Émile Blanche', 'jacques-emile-blanche', 1942),
('James Cassie', 'james-cassie', 1879),
('James Ensor', 'james-ensor', 1949),
('James Giles', 'james-giles', 1870),
('James Hamilton', 'james-hamilton', 1878),
('James Henry Beard', 'james-henry-beard', 1893),
('James Jebusa Shannon', 'james-jebusa-shannon', 1923),
('James McNeill Whistler', 'james-mcneill-whistler', 1903),
('James Smetham', 'james-smetham', 1899),
('James Tissot', 'james-tissot', 1902),
('James Ward', 'james-ward', 1859),
('Jan Ciągliński', 'jan-ciaglinski', 1913),
('Jan Steen', 'jan-steen', 1679),
('Jan Van Beers', 'jan-van-beers', 1927),
('Jan Verkolje', 'jan-verkolje', 1693),
('Jasper Francis Cropsey', 'jasper-francis-cropsey', 1900),
('Jean Baptiste Vanmour', 'jean-baptiste-vanmour', 1737),
('Jean Delville', 'jean-delville', 1953),
('Jean François de Troy', 'jean-francois-de-troy', 1752),
('Jean Geoffroy', 'jean-geoffroy', 1924),
('Jean-Auguste-Dominique Ingres', 'jean-auguste-dominique-ingres', 1867),
('Jean-Baptiste Oudry', 'jean-baptiste-oudry', 1755),
('Jean-Baptiste-Camille Corot', 'jean-baptiste-camille-corot', 1875),
('Jean-Étienne Liotard', 'jean-etienne-liotard', 1789),
('Jean-François Gigoux', 'jean-francois-gigoux', 1894),
('Jean-François Millet', 'jean-francois-millet', 1875),
('Jean-François Raffaëlli', 'jean-francois-raffaelli', 1924),
('Jean-Honoré Fragonard', 'jean-honore-fragonard', 1806),
('Jean-Jacques Scherrer', 'jean-jacques-scherrer', 1916),
('Jean-Joseph Benjamin-Constant', 'jean-joseph-benjamin-constant', 1902),
('Jean-Léon Gérôme', 'jean-leon-gerome', 1904),
('Jean-Marc Nattier', 'jean-marc-nattier', 1766),
('Jean-Paul Laurens', 'jean-paul-laurens', 1921),
('Jehan-Georges Vibert', 'jehan-georges-vibert', 1902),
('Jessie Willcox Smith', 'jessie-willcox-smith', 1935),
('Joaquín Sorolla', 'joaquin-sorolla', 1923),
('Johan Barthold Jongkind', 'johan-barthold-jongkind', 1891),
('Johan Christian Dahl', 'johan-christian-dahl', 1857),
('Johan Heinrich Neuman', 'johan-heinrich-neuman', 1898),
('Johan Rohde', 'johan-rohde', 1935),
('Johan Vilhelm Gertner', 'johan-vilhelm-gertner', 1871),
('Johan Zoffany', 'johan-zoffany', 1810),
('Johann Heinrich Ramberg', 'johann-heinrich-ramberg', 1840),
('Johannes Tavenraat', 'johannes-tavenraat', 1881),
('Johannes Vermeer', 'johannes-vermeer', 1675),
('John Atkinson Grimshaw', 'john-atkinson-grimshaw', 1893),
('John Buxton Knight', 'john-buxton-knight', 1908),
('John Charles Dollman', 'john-charles-dollman', 1934),
('John Christen Johansen', 'john-christen-johansen', 1964),
('John Collier', 'john-collier', 1934),
('John Constable', 'john-constable', 1837),
('John Covert', 'john-covert', 1960),
('John Everett Millais', 'john-everett-millais', 1896),
('John F. Francis', 'john-f-francis', 1886),
('John F. Peto', 'john-f-peto', 1907),
('John Frederick Kensett', 'john-frederick-kensett', 1872),
('John Fulleylove', 'john-fulleylove', 1908),
('John Gilbert', 'john-gilbert', 1897),
('John Hayls', 'john-hayls', 1679),
('John Henry Twachtman', 'john-henry-twachtman', 1902),
('John Hoppner', 'john-hoppner', 1810),
('John Inigo Richards', 'john-inigo-richards', 1810),
('John La Farge', 'john-la-farge', 1910),
('John Linnell', 'john-linnell', 1882),
('John Opie', 'john-opie', 1807),
('John O’Brien Inman', 'john-obrien-inman', 1896),
('John Robert Cozens', 'john-robert-cozens', 1797),
('John Robertson Reid', 'john-robertson-reid', 1926),
('John Simpson', 'john-simpson', 1847),
('John Singer Sargent', 'john-singer-sargent', 1925),
('John Singleton Copley', 'john-singleton-copley', 1815),
('John Taylor', 'john-taylor', 1651),
('John White Alexander', 'john-white-alexander', 1915),
('John William Waterhouse', 'john-william-waterhouse', 1917),
('John Wollaston', 'john-wollaston', 1775),
('John Woodhouse Audubon', 'john-woodhouse-audubon', 1862),
('Josef Presser', 'josef-presser', 1967),
('Joseph Anton Koch', 'joseph-anton-koch', 1839),
('Joseph Ducreux', 'joseph-ducreux', 1802),
('Joseph Magnus Stäck', 'joseph-magnus-stack', 1868),
('Joseph Michael Gleeson', 'joseph-michael-gleeson', 1917),
('Joseph Noel Paton', 'joseph-noel-paton', 1901),
('Joseph Paelinck', 'joseph-paelinck', 1839),
('Joseph Severn', 'joseph-severn', 1879),
('Joseph-Marie Vien', 'joseph-marie-vien', 1809),
('Joshua Reynolds', 'joshua-reynolds', 1792),
('Józef Brandt', 'jozef-brandt', 1915),
('Jozef Israëls', 'jozef-israels', 1911),
('József Rippl-Rónai', 'jozsef-rippl-ronai', 1927),
('Juan Gris', 'juan-gris', 1927),
('Juana Romani', 'juana-romani', 1924),
('Jules Breton', 'jules-breton', 1906),
('Jules Dupré', 'jules-dupre', 1889),
('Jules-Alexis Muenier', 'jules-alexis-muenier', 1942),
('Julian Alden Weir', 'julian-alden-weir', 1919),
('Julian Ashton', 'julian-ashton', 1942),
('Karl Friedrich Schinkel', 'karl-friedrich-schinkel', 1841),
('Kate Bisschop-Swift', 'kate-bisschop-swift', 1928),
('Kenyon Cox', 'kenyon-cox', 1919),
('Knud Baade', 'knud-baade', 1879),
('Konstantin Korovin', 'konstantin-korovin', 1939),
('L. Birge Harrison', 'l-birge-harrison', 1929),
('Laurent Dabos', 'laurent-dabos', 1835),
('Lawren Harris', 'lawren-harris', 1970),
('Lawrence Alma-Tadema', 'lawrence-alma-tadema', 1912),
('Léon Bonnat', 'leon-bonnat', 1922),
('Léon Comerre', 'leon-comerre', 1916),
('Leon Engers Kennedy', 'leon-engers-kennedy', 1970),
('Léon Frédéric', 'leon-frederic', 1940),
('Leonid Pasternak', 'leonid-pasternak', 1945),
('Lesser Ury', 'lesser-ury', 1931),
('Lilly Martin Spencer', 'lilly-martin-spencer', 1902),
('Lionel Royer', 'lionel-royer', 1926),
('Louis Candide Boulanger', 'louis-candide-boulanger', 1867),
('Louis Eilshemius', 'louis-eilshemius', 1941),
('Louis Gurlitt', 'louis-gurlitt', 1897),
('Louis Welden Hawkins', 'louis-welden-hawkins', 1910),
('Louis Wiesenberg', 'louis-wiesenberg', 1943),
('Louis-Léopold Boilly', 'louis-leopold-boilly', 1845),
('Lucien Simon', 'lucien-simon', 1945),
('Ludwig Deutsch', 'ludwig-deutsch', 1935),
('Luigi Russolo', 'luigi-russolo', 1947),
('Luis Meléndez', 'luis-melendez', 1780),
('Magnus Enckell', 'magnus-enckell', 1925),
('Marc Chagall', 'marc-chagall', 1985),
('Marcel Duchamp', 'marcel-duchamp', 1968),
('Marcus Larson', 'marcus-larson', 1864),
('Marie Bashkirtseff', 'marie-bashkirtseff', 1884),
('Marsden Hartley', 'marsden-hartley', 1943),
('Martin Archer Shee', 'martin-archer-shee', 1850),
('Martin Johnson Heade', 'martin-johnson-heade', 1904),
('Mary Cassatt', 'mary-cassatt', 1926),
('Matthijs Maris', 'matthijs-maris', 1917),
('Maurice Denis', 'maurice-denis', 1943),
('Maurice Quentin de La Tour', 'maurice-quentin-de-la-tour', 1788),
('Max Brödel', 'max-brodel', 1941),
('Maxime Maufra', 'maxime-maufra', 1918),
('Melchior d’Hondecoeter', 'melchior-dhondecoeter', 1695),
('Michelangelo da Caravaggio', 'michelangelo-da-caravaggio', 1610),
('Michele Catti', 'michele-catti', 1914),
('Michiel Sweerts', 'michiel-sweerts', 1664),
('Mikalojus Konstantinas Čiurlionis', 'mikalojus-konstantinas-ciurlionis', 1911),
('Mikhail Vrubel', 'mikhail-vrubel', 1910),
('Moritz von Schwind', 'moritz-von-schwind', 1871),
('N. C. Wyeth', 'n-c-wyeth', 1945),
('Nicolai Abildgaard', 'nicolai-abildgaard', 1809),
('Nicolas Poussin', 'nicolas-poussin', 1665),
('Nikolai Yaroshenko', 'nikolai-yaroshenko', 1898),
('Nils Kreuger', 'nils-kreuger', 1930),
('Norman Rockwell', 'norman-rockwell', 1978),
('Odilon Redon', 'odilon-redon', 1916),
('Ole Peter Hansen Balling', 'ole-peter-hansen-balling', 1906),
('Orlando Rouland', 'orlando-rouland', 1945),
('Oscar Konrad Kleineh', 'oscar-konrad-kleineh', 1919),
('Osip Braz', 'osip-braz', 1936),
('Pablo Picasso', 'pablo-picasso', 1973),
('Paolo Veronese', 'paolo-veronese', 1588),
('Paul Bransom', 'paul-bransom', 1979),
('Paul Cézanne', 'paul-cezanne', 1906),
('Paul Gauguin', 'paul-gauguin', 1903),
('Paul Nash', 'paul-nash', 1946),
('Paul-Jacques-Aimé Baudry', 'paul-jacques-aime-baudry', 1886),
('Peder Severin Krøyer', 'peder-severin-kroyer', 1909),
('Peter Alfred Schou', 'peter-alfred-schou', 1914),
('Peter Graham', 'peter-graham', 1921),
('Peter Ilsted', 'peter-ilsted', 1933),
('Peter Nicolai Arbo', 'peter-nicolai-arbo', 1892),
('Peter Paul Rubens', 'peter-paul-rubens', 1640),
('Pierre Auguste Cot', 'pierre-auguste-cot', 1883),
('Pierre Jean Van der Ouderaa', 'pierre-jean-van-der-ouderaa', 1915),
('Pierre-Auguste Renoir', 'pierre-auguste-renoir', 1919),
('Pieter Bruegel the Elder', 'pieter-bruegel-the-elder', 1569),
('Pieter de Hooch', 'pieter-de-hooch', 1684),
('Pieter Gerardus van Os', 'pieter-gerardus-van-os', 1839),
('Pieter Huys', 'pieter-huys', 1584),
('Pieter van der Willigen', 'pieter-van-der-willigen', 1694),
('Pompeo Batoni', 'pompeo-batoni', 1787),
('Prince Eugen', 'prince-eugen', 1947),
('Ralph Albert Blakelock', 'ralph-albert-blakelock', 1919),
('Ralph Peacock', 'ralph-peacock', 1946),
('Raphael', 'raphael', 1520),
('Rembrandt van Rijn', 'rembrandt-van-rijn', 1669),
('Richard Ansdell', 'richard-ansdell', 1885),
('Richard Bergh', 'richard-bergh', 1919),
('Richard Caton Woodville', 'richard-caton-woodville', 1855),
('Richard Jack', 'richard-jack', 1952),
('Richard Norris Brooke', 'richard-norris-brooke', 1920),
('Richard Wilson', 'richard-wilson', 1782),
('Robert Delaunay', 'robert-delaunay', 1941),
('Robert Henri', 'robert-henri', 1929),
('Robert Koehler', 'robert-koehler', 1917),
('Robert Lee MacCameron', 'robert-lee-maccameron', 1912),
('Robert Lewis Reid', 'robert-lewis-reid', 1929),
('Roger de la Fresnaye', 'roger-de-la-fresnaye', 1925),
('Rosa Bonheur', 'rosa-bonheur', 1899),
('Salomon van Abbé', 'salomon-van-abbe', 1955),
('Samuel Henry Baker', 'samuel-henry-baker', 1909),
('Samuel Laurence', 'samuel-laurence', 1884),
('Samuel Luke Fildes', 'samuel-luke-fildes', 1927),
('Samuel Scott', 'samuel-scott', 1772),
('Santi di Tito', 'santi-di-tito', 1603),
('Sasza Blonder', 'sasza-blonder', 1949),
('Simon Maris', 'simon-maris', 1935),
('Stanislawa de Karlowska', 'stanislawa-de-karlowska', 1952),
('Stanisław Witkiewicz', 'stanislaw-witkiewicz', 1915),
('Stephen Pearce', 'stephen-pearce', 1904),
('Stuart Walker', 'stuart-walker', 1940),
('Théodore Géricault', 'theodore-gericault', 1824),
('Thomas Anshutz', 'thomas-anshutz', 1912),
('Thomas Churchyard', 'thomas-churchyard', 1865),
('Thomas Cole', 'thomas-cole', 1848),
('Thomas Daniell', 'thomas-daniell', 1840),
('Thomas Duncan', 'thomas-duncan', 1845),
('Thomas Eakins', 'thomas-eakins', 1916),
('Thomas Faed', 'thomas-faed', 1900),
('Thomas Gainsborough', 'thomas-gainsborough', 1788),
('Thomas Lawrence', 'thomas-lawrence', 1830),
('Thomas Moran', 'thomas-moran', 1926),
('Tiziano Vecellio', 'tiziano-vecellio', 1576),
('Tom Roberts', 'tom-roberts', 1931),
('Tom Thomson', 'tom-thomson', 1917),
('Umberto Boccioni', 'umberto-boccioni', 1916),
('Vasily Surikov', 'vasily-surikov', 1916),
('Vasily Vereshchagin', 'vasily-vereshchagin', 1904),
('Victor Dubreuil', 'victor-dubreuil', 1946),
('Victor Westerholm', 'victor-westerholm', 1919),
('Viktor Vasnetsov', 'viktor-vasnetsov', 1926),
('Vilhelm Hammershøi', 'vilhelm-hammershoi', 1916),
('Vilhelm Lundstrøm', 'vilhelm-lundstrom', 1950),
('Vincent Van Gogh', 'vincent-van-gogh', 1890),
('Walter Frederick Osborne', 'walter-frederick-osborne', 1903),
('Walter S. Rogers', 'walter-s-rogers', 1937),
('Walter Sickert', 'walter-sickert', 1942),
('Walter William Ouless', 'walter-william-ouless', 1933),
('Wang Hui', 'wang-hui', 1717),
('Wassily Kandinsky', 'wassily-kandinsky', 1944),
('Wilhelm Kotarbiński', 'wilhelm-kotarbinski', 1921),
('Wilhelm von Kaulbach', 'wilhelm-von-kaulbach', 1874),
('Willard Metcalf', 'willard-metcalf', 1925),
('Willem Claesz Heda', 'willem-claesz-heda', 1680),
('Willem Joseph Laquy', 'willem-joseph-laquy', 1798),
('Willem Kalf', 'willem-kalf', 1693),
('Willem van de Velde the Younger', 'willem-van-de-velde-the-younger', 1707),
('William A. Coffin', 'william-a-coffin', 1925),
('William Blake Richmond', 'william-blake-richmond', 1921),
('William Bradford', 'william-bradford', 1892),
('William Collins', 'william-collins', 1847),
('William Fettes Douglas', 'william-fettes-douglas', 1891),
('William Glackens', 'william-glackens', 1938),
('William H. Schenck', 'william-h-schenck', 1864),
('William Harnett', 'william-harnett', 1892),
('William Hodges', 'william-hodges', 1797),
('William Hogarth', 'william-hogarth', 1764),
('William Holbrook Beard', 'william-holbrook-beard', 1900),
('William Holman Hunt', 'william-holman-hunt', 1910),
('William J. Edmondson', 'william-j-edmondson', 1966),
('William Lister Lister', 'william-lister-lister', 1943),
('William Logsdail', 'william-logsdail', 1944),
('William McGregor Paxton', 'william-mcgregor-paxton', 1941),
('William Merritt Chase', 'william-merritt-chase', 1916),
('William Michaud von Vevey', 'william-michaud-von-vevey', 1902),
('William Mulready', 'william-mulready', 1863),
('William Orpen', 'william-orpen', 1931),
('William Powell Frith', 'william-powell-frith', 1909),
('William Quiller Orchardson', 'william-quiller-orchardson', 1910),
('William Robinson Leigh', 'william-robinson-leigh', 1955),
('William Segar', 'william-segar', 1633),
('William Simpson', 'william-simpson', 1899),
('William Sydney Mount', 'william-sydney-mount', 1868),
('William-Adolphe Bouguereau', 'william-adolphe-bouguereau', 1905),
('Winslow Homer', 'winslow-homer', 1910),
('Wouter Johannes van Troostwijk', 'wouter-johannes-van-troostwijk', 1810);
