CREATE TABLE IF NOT EXISTS `Artworks` (
  `ArtworkId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ArtistId` int(10) unsigned NOT NULL,
  `Name` varchar(255) NOT NULL,
  `UrlName` varchar(255) NOT NULL,
  `CompletedYear` smallint(5) unsigned DEFAULT NULL,
  `CompletedYearIsCirca` tinyint(1) NOT NULL DEFAULT 0,
  `Status` enum('unverified','approved','declined','in_use') NOT NULL DEFAULT 'unverified',
  `SubmitterUserId` int(11) unsigned DEFAULT NULL,
  `ReviewerUserId` int(10) unsigned DEFAULT NULL,
  `IsAutoReviewed` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `MuseumUrl` varchar(255) DEFAULT NULL,
  `PublicationYear` smallint(5) unsigned DEFAULT NULL,
  `PublicationYearPageUrl` varchar(255) DEFAULT NULL,
  `CopyrightPageUrl` varchar(255) DEFAULT NULL,
  `ArtworkPageUrl` varchar(255) DEFAULT NULL,
  `IsPublishedInUs` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `EbookId` int(10) unsigned DEFAULT NULL,
  `MimeType` enum('image/jpeg','image/bmp','image/png','image/tiff','image/webp') NOT NULL,
  `Exception` text DEFAULT NULL,
  `Notes` text DEFAULT NULL,
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `CreatedAt` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ArtworkId`),
  KEY `Status` (`Status`),
  KEY `UrlName` (`UrlName`),
  KEY `ArtistId` (`ArtistId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
