CREATE TABLE IF NOT EXISTS `se`.`BlogPosts` (
  `BlogPostId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserId` INT UNSIGNED NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Subtitle` VARCHAR(255) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `UrlTitle` VARCHAR(255) NOT NULL,
  `Body` LONGTEXT NULL,
  `Published` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`BlogPostId`),
  UNIQUE KEY `index2` (`UrlTitle`),
  KEY `index3` (`Published` ASC)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
