CREATE TABLE IF NOT EXISTS `Ebooks` (
  `EbookId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Identifier` varchar(511) NOT NULL,
  `WwwFilesystemPath` varchar(511) NULL,
  `RepoFilesystemPath` varchar(511) NULL,
  `KindleCoverUrl` varchar(511) NULL,
  `EpubUrl` varchar(511) NULL,
  `AdvancedEpubUrl` varchar(511) NULL,
  `KepubUrl` varchar(511) NULL,
  `Azw3Url` varchar(511) NULL,
  `DistCoverUrl` varchar(511) NULL,
  `CoverImageKey` char(40) NULL,
  `Title` varchar(255) NOT NULL,
  `FullTitle` varchar(255) NULL,
  `AlternateTitle` varchar(255) NULL,
  `ShortTitle` varchar(255) NULL,
  `Description` text NULL,
  `LongDescription` text NULL,
  `Language` varchar(10) NULL,
  `WordCount` int(10) unsigned NULL,
  `ReadingEase` float NULL,
  `GitHubUrl` varchar(255) NULL,
  `WikipediaUrl` varchar(255) NULL,
  `EbookCreatedAt` datetime NULL,
  `EbookUpdatedAt` datetime NULL,
  `TextSinglePageByteCount` bigint unsigned NULL,
  `DownloadsPast30Days` int(10) unsigned NOT NULL DEFAULT 0,
  `DownloadsTotal` int(10) unsigned NOT NULL DEFAULT 0,
  `IsPatronSelection` boolean NOT NULL DEFAULT FALSE,
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `CreatedAt` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`EbookId`),
  UNIQUE KEY `Identifier` (`Identifier`),
  KEY `EbookCreatedAt` (`EbookCreatedAt`),
  KEY `DownloadsPast30Days_EbookCreatedAt` (`DownloadsPast30Days` DESC, `EbookCreatedAt` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
