CREATE TABLE IF NOT EXISTS `NewsletterMailings` (
  `NewsletterMailingId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NewsletterId` int(10) unsigned NOT NULL,
  `ExcludePatrons` tinyint(1) NOT NULL DEFAULT FALSE,
  `Status` enum('queued','processing','completed','failed','canceled') NOT NULL DEFAULT 'queued',
  `Subject` varchar(255) NOT NULL,
  `Preheader` varchar(255) NULL DEFAULT NULL,
  `BodyHtml` text NOT NULL,
  `BodyText` text NOT NULL,
  `FromName` varchar(255) DEFAULT NULL,
  `FromEmail` varchar(255) NOT NULL,
  `SendAt` datetime NOT NULL,
  `RecipientCount` int(10) unsigned DEFAULT NULL,
  `OpenCount` int(10) unsigned DEFAULT NULL,
  `InternalName` varchar(255) DEFAULT NULL,
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `CreatedAt` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`NewsletterMailingId`),
  KEY `Status_SendAt` (`Status`,`SendAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
