CREATE TABLE IF NOT EXISTS `Projects` (
  `ProjectId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Status` enum('in_progress','awaiting_review','reviewed','stalled','completed','abandoned') NOT NULL DEFAULT 'in_progress',
  `EbookId` int(11) NOT NULL,
  `ProducerUserId` int(10) unsigned NOT NULL,
  `DiscussionUrl` varchar(255) DEFAULT NULL,
  `VcsUrl` varchar(255) DEFAULT NULL,
  `StartedAt` datetime NOT NULL,
  `EndedAt` datetime DEFAULT NULL,
  `ManagerUserId` int(11) NOT NULL,
  `ReviewerUserId` int(11) NOT NULL,
  `LastCommitAt` DATETIME NULL DEFAULT NULL,
  `LastDiscussionAt` DATETIME NULL DEFAULT NULL,
  `IsStatusAutomaticallyUpdated` tinyint(1) NOT NULL DEFAULT 1,
  `HasReviewerBeenNotified` tinyint(1) NOT NULL DEFAULT 0,
  `AreDiscussionMessagesComplete` tinyint(1) NOT NULL DEFAULT 0,
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `CreatedAt` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ProjectId`),
  KEY `EbookId` (`EbookId`),
  KEY `ProducerUserId` (`ProducerUserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
