<?
use Safe\DateTimeImmutable;

use function Safe\file_get_contents;
use function Safe\ini_get;
use function Safe\glob;
use function Safe\preg_match;
use function Safe\preg_replace;
use function Safe\mb_convert_encoding;

class HttpInput{
	/** The *calculated* method of this HTTP request based on the real HTTP method and the presence of a `_method` parameter, or `null` if the calculated method is invalid (e.g. `_method=NOTAMETHOD`). Generated by default on framework initialization and can be recalculated using `HttpInput::CalculateRequestMethod()`. */
	public static ?Enums\HttpMethod $RequestMethod;
	public static Enums\HttpRequestType $RequestType = Enums\HttpRequestType::Rest;

	/** @var array<Enums\HttpMethod> The allowed HTTP methods calculated for this request. */
	private static array $_AllowedHttpMethods;

	/**
	 * Calculate the request method given a `_method` parameter in the request, and populate `$_POST` with data from non-`POST` requests (e.g. `DELETE`, `PATCH`, or `PUT`).
	 *
	 * This can't handle file uploads, which due to PHP limitations *must* be sent via `POST`.
	 */
	public static function Initialize(): void{
		/** @var string $contentType */
		$contentType = $_SERVER['CONTENT_TYPE'] ?? '';
		if(
			isset($_SERVER['REQUEST_METHOD'])
			&&
			(
				$_SERVER['REQUEST_METHOD'] == Enums\HttpMethod::Delete->value
				||
				$_SERVER['REQUEST_METHOD'] == Enums\HttpMethod::Patch->value
				||
				$_SERVER['REQUEST_METHOD'] == Enums\HttpMethod::Put->value
			)
			&&
			preg_match('/^application\/x-www-form-urlencoded(;|$)/', $contentType)
		){
			// TODO: On PHP >= 8.4, use the new `request_parse_body()` function instead.
			parse_str(file_get_contents('php://input'), $_POST);
		}

		// Calculate the request method, don't allow `_method` parameters in GET requests by default to prevent CSRF.
		self::CalculateRequestMethod();

		// Calculate the request type, i.e., did a browser make this request, or a REST call?
		/** @var string $httpAccept */
		$httpAccept = $_SERVER['HTTP_ACCEPT'] ?? '';
		self::$RequestType = preg_match('/(^|,|\s)(text\/html|application\/xhtml\+xml|\*\/\*)(;|,|\s|$)/ius', $httpAccept) ? Enums\HttpRequestType::Browser : Enums\HttpRequestType::Rest;
	}

	/**
	 * Calculate the request method based on the presence of a `_method` parameter in the request.
	 *
	 * @param bool $allowGet **`TRUE`** to allow `_method` parameters in `GET` requests to set the HTTP method. Useful for links that appear in emails, but should be disabled otherwise to prevent CSRF attacks.
	 */
	public static function CalculateRequestMethod(bool $allowGet = false): void{
		if($allowGet){
			/** @var string $requestMethodString */
			$requestMethodString = $_POST['_method'] ?? $_GET['_method'] ?? $_SERVER['REQUEST_METHOD'] ?? '';
		}
		else{
			/** @var string $requestMethodString */
			$requestMethodString = $_POST['_method'] ?? $_SERVER['REQUEST_METHOD'] ?? '';
		}

		self::$RequestMethod = Enums\HttpMethod::tryFrom(strtoupper($requestMethodString));
	}

	/**
	 * Calculate the HTTP method of the request, then include `http-<METHOD>.php` and exit.
	 *
	 * @param ?array<Enums\HttpMethod> $allowedHttpMethods An exhaustive list of allowed HTTP methods, or `null` to determine the allowed methods based on which method logic files exist in the current directory.
	 * @param mixed $resource An optional object to pass as a global variable to the method logic file.
	 */
	public static function RouteRequest(?array $allowedHttpMethods = null, mixed $resource = null): void{
		$allowedHttpMethods = HttpInput::GetAllowedHttpMethods($allowedHttpMethods);

		if(!in_array(self::$RequestMethod, $allowedHttpMethods)){
			self::OutputAllowedHttpMethods($allowedHttpMethods);
			http_response_code(Enums\HttpCode::MethodNotAllowed->value);
			exit();
		}

		if(self::$RequestMethod == Enums\HttpMethod::Options){
			self::OutputAllowedHttpMethods($allowedHttpMethods);
			http_response_code(Enums\HttpCode::NoContent->value);
			exit();
		}

		$filename = 'http-' . mb_strtolower(self::$RequestMethod->value ?? '') . '.php';

		// `HEAD` is always allowed if `GET` is allowed.
		if(self::$RequestMethod == Enums\HttpMethod::Head && !file_exists('http-head.php')){
			$filename = 'http-get.php';
		}

		if(!file_exists($filename)){
			self::OutputAllowedHttpMethods($allowedHttpMethods);
			http_response_code(Enums\HttpCode::MethodNotAllowed->value);
			exit();
		}

		// If we didn't include a `$resource`, unset the variable. Otherwise, it's automatically passed as a global to the following included file.
		if($resource === null){
			unset($resource);
		}

		/** @phpstan-ignore-next-line */
		include($filename);

		exit();
	}

	/**
	 * Calculate the allowed HTTP methods for the currently running script.
	 *
	 * If any `http-*.php` files are found in the current directory, the only allowed methods are those files and OPTIONS. Otherwise, `GET`, `HEAD`, and `OPTIONS` are the only allowed methods.
	 *
	 * @param ?array<Enums\HttpMethod> $allowedHttpMethods
	 *
	 * @return array<Enums\HttpMethod>
	 */
	private static function GetAllowedHttpMethods(?array $allowedHttpMethods = null): array{
		if(!isset(self::$_AllowedHttpMethods)){
			if($allowedHttpMethods === null){
				$allowedHttpMethods = [];

				$filenames = glob('http-{connect,delete,get,head,options,patch,post,put,trace}.php', GLOB_BRACE);

				foreach($filenames as $filename){
					try{
						$allowedHttpMethods[] = Enums\HttpMethod::from(strtoupper(preg_replace('/^http-|\.php$/iu', '', $filename)));
					}
					catch(\ValueError){
						// Invalid method, continue.
					}
				}
			}

			// HTTP HEAD is always allowed if HTTP GET is allowed.
			if(in_array(Enums\HttpMethod::Get, $allowedHttpMethods) && !in_array(Enums\HttpMethod::Head, $allowedHttpMethods)){
				$allowedHttpMethods[] = Enums\HttpMethod::Head;
			}

			// HTTP OPTIONS is always allowed.
			if(!in_array(Enums\HttpMethod::Options, $allowedHttpMethods)){
				$allowedHttpMethods[] = Enums\HttpMethod::Options;
			}

			// If this file is `PATCH`, `PUT`, or `DELETE`, then we don't allow `POST` at this endpoint.
			// E.g. if this file is `PATCH /employees/123` then we don't allow `POST /employees/123` (instead, we should `POST /employees`)...
			// TODO ...but, we must tunnel non-`GET` requests submitted via HTML forms using `POST`. So, always allow `POST` in those cases. For now, this block is commented out until we ascend to the nirvana of HTML forms allowing non-`POST` methods. See <https://github.com/whatwg/html/pull/11347>.
			/*
			if(
				in_array(Enums\HttpMethod::Delete, $allowedHttpMethods)
				||
				in_array(Enums\HttpMethod::Patch, $allowedHttpMethods)
				||
				in_array(Enums\HttpMethod::Put, $allowedHttpMethods)
			){
				$newMethods = [];
				foreach($allowedHttpMethods as $method){
					if($method != Enums\HttpMethod::Post){
						$newMethods[] = $method;
					}
				}
				$allowedHttpMethods = $newMethods;
			}
			*/
			// See above... if we allow `DELETE`, `PATCH`, or `PUT`, allow tunneling through `POST`.
			if(
				!in_array(Enums\HttpMethod::Post, $allowedHttpMethods)
				&&
				(
					in_array(Enums\HttpMethod::Delete, $allowedHttpMethods)
					||
					in_array(Enums\HttpMethod::Patch, $allowedHttpMethods)
					||
					in_array(Enums\HttpMethod::Put, $allowedHttpMethods)
				)
			){
				$allowedHttpMethods[] = Enums\HttpMethod::Post;
			}

			// Sort the final array.
			usort($allowedHttpMethods, fn(BackedEnum $a, BackedEnum $b): int => strcasecmp((string)$a->value, (string)$b->value));

			self::$_AllowedHttpMethods = $allowedHttpMethods;
		}

		return self::$_AllowedHttpMethods;
	}

	/**
	 * Calculate the allowed HTTP methods for the currently running script and output HTTP headers advertising them.
	 *
	 * @param ?array<Enums\HttpMethod> $allowedHttpMethods An array containing a list of allowed HTTP methods, or `null` to calculate them based on router files.
	 */
	private static function OutputAllowedHttpMethods(?array $allowedHttpMethods = null): void{
		$allowedHttpMethods = $allowedHttpMethods ?? self::GetAllowedHttpMethods();

		if(sizeof($allowedHttpMethods) > 0){
			header('allow: ' . implode(',', array_map(fn($httpMethod): string => $httpMethod->value, $allowedHttpMethods)));
		}

		if(in_array(Enums\HttpMethod::Patch, $allowedHttpMethods)){
			header('accept-patch: application/x-www-form-urlencoded,multipart/form-data');
		}

		if(in_array(Enums\HttpMethod::Post, $allowedHttpMethods)){
			header('accept-post: application/x-www-form-urlencoded,multipart/form-data');
		}
	}

	/**
	 * @return int The maximum size for an HTTP `POST` request, in bytes.
	 */
	public static function GetMaxPostSize(): int{
		$post_max_size = ini_get('upload_max_filesize');
		$unit = substr($post_max_size, -1);
		$size = (int) substr($post_max_size, 0, -1);

		return match ($unit){
			'g', 'G' => $size * 1024 * 1024 * 1024,
			'm', 'M' => $size * 1024 * 1024,
			'k', 'K' => $size * 1024,
			default => $size
		};
	}

	public static function IsRequestTooLarge(): bool{
		if(empty($_POST) || empty($_FILES)){
			if($_SERVER['CONTENT_LENGTH'] > self::GetMaxPostSize()){
				return true;
			}
		}

		// We received files but may have an error because the size exceeded our limit.
		foreach($_FILES as $file){
			/** @var array<string, int> $file */
			$error = $file['error'] ?? UPLOAD_ERR_OK;

			if($error == UPLOAD_ERR_INI_SIZE || $error == UPLOAD_ERR_FORM_SIZE){
				return true;
			}
		}

		return false;
	}

	/**
	 * Get a string from an HTTP variable set.
	 *
	 * If the variable is set but empty, returns `null` unless `$allowEmptyString` is **`TRUE`**, in which case it returns an empty string.
	 *
	 * @param Enums\HttpVariableSource $set
	 * @param string $variable
	 * @param bool $allowEmptyString If the variable exists but is empty, return an empty string instead of `null`.
	 */
	public static function Str(Enums\HttpVariableSource $set, string $variable, bool $allowEmptyString = false): ?string{
		$var = self::GetHttpVar($variable, Enums\HttpVariableType::String, $set);

		if(is_array($var)){
			return null;
		}

		if(!$allowEmptyString && $var == ''){
			return null;
		}

		/** @var ?string $var */
		return $var;
	}

	public static function Int(Enums\HttpVariableSource $set, string $variable): ?int{
		/** @var ?int */
		return self::GetHttpVar($variable, Enums\HttpVariableType::Integer, $set);
	}

	public static function Bool(Enums\HttpVariableSource $set, string $variable): ?bool{
		/** @var ?bool */
		return self::GetHttpVar($variable, Enums\HttpVariableType::Boolean, $set);
	}

	public static function Dec(Enums\HttpVariableSource $set, string $variable): ?float{
		/** @var ?float */
		return self::GetHttpVar($variable, Enums\HttpVariableType::Decimal, $set);
	}

	public static function Date(Enums\HttpVariableSource $set, string $variable): ?DateTimeImmutable{
		/** @var ?DateTimeImmutable */
		return self::GetHttpVar($variable, Enums\HttpVariableType::DateTime, $set);
	}

	/**
	 * Return an object of type `$class` from `$_SESSION`, or `null` of no object of that type exists in `$_SESSION`.
	 *
	 * @template T of object
	 * @param string $variable
	 * @param class-string<T>|array<class-string<T>> $class The class of the object to return, or an array of possible classes to return.
	 *
	 * @return ?T An object of type `$class`, or `null` if no object of that type exists in `$_SESSION`.
	 */
	public static function SessionObject(string $variable, string|array $class): ?object{
		if(!is_array($class)){
			$class = [$class];
		}

		$object = $_SESSION[$variable] ?? null;

		if(is_object($object)){
			foreach($class as $c){
				if(is_a($object, $c)){
					return $object;
				}
			}
		}

		return null;
	}

	/**
	 * Returns the absolute path of the requested file upload, or `null` if there isn't one.
	 *
	 * @throws Exceptions\InvalidFileUploadException If there is a file upload present, but the upload somehow failed.
	 */
	public static function File(string $variable): ?string{
		$filePath = null;

		if(isset($_FILES[$variable])){
			/** @var array{'error': int, 'size': int, 'tmp_name': string} $file */
			$file = $_FILES[$variable];

			if($file['size'] > 0){
				if(!is_uploaded_file($file['tmp_name']) || $file['error'] > UPLOAD_ERR_OK){
					throw new Exceptions\InvalidFileUploadException();
				}

				$filePath = $file['tmp_name'];
			}
		}

		return $filePath;
	}

	/**
	* @param string $variable
	* @return array<string>
	*/
	public static function Array(Enums\HttpVariableSource $set, string $variable): ?array{
		/** @var array<string> */
		return self::GetHttpVar($variable, Enums\HttpVariableType::Array, $set);
	}

	/**
	 * @return array<string>|array<int>|array<float>|array<bool>|array<mixed>|string|int|float|bool|DateTimeImmutable|null
	 */
	private static function GetHttpVar(string $variable, Enums\HttpVariableType $type, Enums\HttpVariableSource $set): mixed{
		$vars = [];

		switch($set){
			case Enums\HttpVariableSource::Get:
				$vars = $_GET;
				break;
			case Enums\HttpVariableSource::Post:
				$vars = $_POST;
				break;
			case Enums\HttpVariableSource::Cookie:
				$vars = $_COOKIE;
				break;
			case Enums\HttpVariableSource::Session:
				$vars = $_SESSION;
				break;
		}

		if(isset($vars[$variable])){
			if($type == Enums\HttpVariableType::Array && is_array($vars[$variable])){
				// We asked for an array, and we got one.
				return $vars[$variable];
			}
			elseif($type !== Enums\HttpVariableType::Array && is_array($vars[$variable])){
				// We asked for not an array, but we got an array.
				return null;
			}
			elseif(is_string($vars[$variable])){
				// HTML `<textarea>`s encode newlines as `\r\n`, i.e. *two* characters, when submitting form data. However jQuery's `.val()` and HTML's `@maxlength` treat newlines as *one* character. So, strip `\r` here so that character lengths align between what the browser reports, and what it actually sends. This also solves column length issues when storing in the DB.
				$var = trim(str_replace("\r", "", $vars[$variable]));
			}
			else{
				$var = $vars[$variable];
			}

			switch($type){
				case Enums\HttpVariableType::String:
					if(!is_string($var)){
						return '';
					}

					// Attempt to fix broken UTF8 strings, often passed by bots and scripts.
					// Broken UTF8 can cause exceptions in functions like `preg_replace()`.
					try{
						return mb_convert_encoding($var, 'utf-8');
					}
					catch(\Safe\Exceptions\MbstringException){
						return '';
					}
				case Enums\HttpVariableType::Integer:
					// Can't use `ctype_digit()` because we may want negative integers.
					if(is_numeric($var) && mb_strpos((string)$var, '.') === false){
						return intval($var);
					}
					break;
				case Enums\HttpVariableType::Boolean:
					if($var === false || (is_string($var) && ($var === '0' || strtolower($var) == 'false' || strtolower($var) == 'off'))){
						return false;
					}
					else{
						return true;
					}
				case Enums\HttpVariableType::Decimal:
					if(is_numeric($var)){
						return floatval($var);
					}
					break;
				case Enums\HttpVariableType::DateTime:
					if(is_string($var) && $var != ''){
						try{
							return new DateTimeImmutable($var);
						}
						catch(Exception){
							return null;
						}
					}
					break;
			}
		}

		return null;
	}
}
