<?
use function Safe\file_get_contents;
use function Safe\glob;
use function Safe\ini_get;
use function Safe\preg_match;
use function Safe\preg_replace;

/**
 * The HTTP request that resulted in this script being run.
 */
class OriginatingHttpRequest{
	/** The *calculated* method of this request based on the real HTTP method and the presence of a `_method` parameter, or `null` if the calculated method is invalid (e.g. `_method=NOTAMETHOD`). Generated by default on framework initialization and can be recalculated using `OriginatingHttpRequest::CalculateRequestMethod()`. */
	public ?Enums\HttpMethod $Method; // TODO: Put this behind a property hook without a setter, because we would like it to be `readonly` but able to be changed via `OriginatingHttpRequest::CalculateRequestMethod()`.
	/** The HTTP method actually used by this request, or `GET` if the method is invalid. */
	public readonly Enums\HttpMethod $RawMethod;
	public readonly HttpVariablesInterface $QueryString;
	public readonly HttpVariablesInterface $Body;
	public readonly HttpVariablesInterface $Cookies;
	/** Unlike other variable interfaces in this class, this reflects the live state of `$_SESSION`. */
	public readonly HttpSessionInterface $Session;
	public readonly HttpFilesInterface $Files;
	/** @var array<string, string> $Headers The HTTP headers for this request, with keys converted to lowercase. */
	public readonly array $Headers;
	/** The relative URI of this request, including the query string, but excluding the domain, e.g. `/users/1`. */
	public readonly string $RelativeUri;
	/** The MIME type of this request. */
	public readonly ?string $ContentType;
	/** The maximum size for an HTTP `POST` request, in bytes. */
	public readonly int $MaxPostSize;
	/** Is this request larger than the size allowed by PHP? This is based on PHP's maximum size of the *entire request*, which may be different from PHP's maximum allowed size for individual file uploads that are *part* of this request. */
	public readonly bool $IsRequestTooLarge;
	/** Does it look like web browser made this request, vs. an API call? */
	public readonly bool $IsViaBrowser;

	/** @var array<Enums\HttpMethod> $_AllowedHttpMethods */
	private array $_AllowedHttpMethods;

	/**
	 * Create an `HttpRequest` representing the request passed to PHP, i.e. with `$_GET`, `$_POST`, etc.
	 */
	public function __construct(){
		// Calculate the maximum request size before proceeding, so we don't read unbounded data.
		$postMaxSize = ini_get('post_max_size');
		if(ctype_digit($postMaxSize)){
			$this->MaxPostSize = intval($postMaxSize);
		}
		else{
			$unit = substr($postMaxSize, -1);
			$size = (int)substr($postMaxSize, 0, -1);

			$this->MaxPostSize = match($unit){
				'g', 'G' => $size * 1024 * 1024 * 1024,
				'm', 'M' => $size * 1024 * 1024,
				'k', 'K' => $size * 1024,
				default => $size
			};
		}

		/** @var string $queryString */
		$queryString = $_SERVER['QUERY_STRING'] ?? '';
		$this->QueryString = new HttpVariablesInterface($queryString, $_GET);

		$headers = [];

		foreach($_SERVER as $key => $value){
			/** @var string $value */
			if(str_starts_with($key, 'HTTP_')){
				$name = strtolower(str_replace('_', '-', substr($key, 5)));
				$headers[$name] = $value;
			}
		}

		/** @var ?string $contentType */
		$contentType = $_SERVER['CONTENT_TYPE'] ?? null;
		$this->ContentType = $contentType;

		if($this->ContentType !== null){
			$headers['content-type'] = $this->ContentType;
		}

		$this->Headers = $headers;

		$this->CalculateRequestMethod();

		/** @var string $method */
		$method = $_SERVER['REQUEST_METHOD'] ?? '';
		$this->RawMethod = Enums\HttpMethod::tryFrom($method) ?? Enums\HttpMethod::Get;

		/** @var string $relativeUri */
		$relativeUri = $_SERVER['REQUEST_URI'] ?? '';
		$this->RelativeUri = $relativeUri;

		/** @var string $httpAccept */
		$httpAccept = $_SERVER['HTTP_ACCEPT'] ?? '';
		$this->IsViaBrowser = (bool)preg_match('/\btext\/html\b/ius', $httpAccept);

		// Decide if this request was too large.
		/** @var ?string $contentLength */
		$contentLength = $_SERVER['CONTENT_LENGTH'] ?? null;

		$this->IsRequestTooLarge = $contentLength !== null && is_numeric($contentLength) && (int)$contentLength > $this->MaxPostSize;

		if($this->IsRequestTooLarge){
			if($this->IsViaBrowser && file_exists(WEB_ROOT . '/413.php')){
				/** @phpstan-ignore-next-line */
				include(WEB_ROOT . '/413.php');
			}

			http_response_code(Enums\HttpCode::ContentTooLarge->value);
			exit();
		}

		if($this->ContentType !== null && preg_match('/^(application\/x-www-form-urlencoded|multipart\/form-data)(;|$)/', $this->ContentType)){
			$variables = [];
			$body = file_get_contents('php://input');

			if($this->RawMethod == Enums\HttpMethod::Post){
				$variables = $_POST;
			}
			else{
				// TODO: On PHP >= 8.4, use the new `request_parse_body()` function instead.
				parse_str($body, $parsedVariables);

				// `parse_str()` may return ints as array keys, normalize that here.
				foreach($parsedVariables as $key => $value){
					if(!is_string($key)){
						$key = strval($key);
					}

					$variables[$key] = $value;
				}
			}

			$this->Body = new HttpVariablesInterface($body, $variables);
		}
		else{
			$this->Body = new HttpVariablesInterface('', []);
		}

		$this->Cookies = new HttpVariablesInterface($this->Headers['cookie'] ?? '', $_COOKIE);

		/** @var array<string, array<string, string>> $files */
		$files = $_FILES;
		$this->Files = new HttpFilesInterface($files);

		$this->Session = new HttpSessionInterface();
	}

	/**
	 * Calculate the request method based on the presence of a `_method` parameter in the request.
	 *
	 * Typically only called internally, but occasionally useful to call externally if we want to allow the `_method` parameter in a query string to change the HTTP method, for example GET requests generated by links in email.
	 *
	 * @param bool $allowGet **`TRUE`** to allow `_method` parameters in `GET` requests to set the HTTP method. Useful for links that appear in emails, but should be disabled otherwise to prevent CSRF attacks.
	 */
	public function CalculateRequestMethod(bool $allowGet = false): void{
		if($allowGet){
			/** @var string $requestMethodString */
			$requestMethodString = $_POST['_method'] ?? $_GET['_method'] ?? $_SERVER['REQUEST_METHOD'] ?? '';
		}
		else{
			/** @var string $requestMethodString */
			$requestMethodString = $_POST['_method'] ?? $_SERVER['REQUEST_METHOD'] ?? '';
		}

		$this->Method = Enums\HttpMethod::tryFrom(strtoupper($requestMethodString));
	}

	/**
	 * Include `http-<METHOD>.php` depending on the *calculated* HTTP method of this request, then exit.
	 *
	 * @param ?array<Enums\HttpMethod> $allowedHttpMethods An exhaustive list of allowed HTTP methods, or `null` to determine the allowed methods based on which method logic files exist in the current directory.
	 * @param mixed $resource An optional object to pass as a global variable to the method logic file.
	 */
	public function Route(?array $allowedHttpMethods = null, mixed $resource = null): void{
		$allowedHttpMethods = $this->GetAllowedHttpMethods($allowedHttpMethods);

		if($this->Method === null || !in_array($this->Method, $allowedHttpMethods)){
			self::OutputAllowedHttpMethods($allowedHttpMethods);
			http_response_code(Enums\HttpCode::MethodNotAllowed->value);
			exit();
		}

		if($this->Method == Enums\HttpMethod::Options){
			self::OutputAllowedHttpMethods($allowedHttpMethods);
			http_response_code(Enums\HttpCode::NoContent->value);
			exit();
		}

		$filename = 'http-' . mb_strtolower($this->Method->value) . '.php';

		// `HEAD` is always allowed if `GET` is allowed.
		if($this->Method == Enums\HttpMethod::Head && !file_exists('http-head.php')){
			$filename = 'http-get.php';
		}

		if(!file_exists($filename)){
			self::OutputAllowedHttpMethods($allowedHttpMethods);
			http_response_code(Enums\HttpCode::MethodNotAllowed->value);
			exit();
		}

		// If we didn't include a `$resource`, unset the variable. Otherwise, it's automatically passed as a global to the following included file.
		if($resource === null){
			unset($resource);
		}

		/** @phpstan-ignore-next-line */
		include($filename);

		exit();
	}

	/**
	 * Calculate the allowed HTTP methods for the currently running script.
	 *
	 * TODO: Put in a property hook.
	 *
	 * If any `http-*.php` files are found in the current directory, the only allowed methods are those files and OPTIONS. Otherwise, `GET`, `HEAD`, and `OPTIONS` are the only allowed methods.
	 *
	 * @param ?array<Enums\HttpMethod> $allowedHttpMethods Only allow these methods, or `null` to calculate the allowed methods based on the presence/absence of `http-*.php` files.
	 *
	 * @return array<Enums\HttpMethod>
	 */
	private function GetAllowedHttpMethods(?array $allowedHttpMethods = null): array{
		if(!isset($this->_AllowedHttpMethods)){
			if($allowedHttpMethods === null){
				$allowedHttpMethods = [];

				$filenames = glob('http-{connect,delete,get,head,options,patch,post,put,trace}.php', GLOB_BRACE);

				foreach($filenames as $filename){
					try{
						$allowedHttpMethods[] = Enums\HttpMethod::from(strtoupper(preg_replace('/^http-|\.php$/iu', '', $filename)));
					}
					catch(\ValueError){
						// Invalid method, continue.
					}
				}
			}

			// HTTP HEAD is always allowed if HTTP GET is allowed.
			if(in_array(Enums\HttpMethod::Get, $allowedHttpMethods) && !in_array(Enums\HttpMethod::Head, $allowedHttpMethods)){
				$allowedHttpMethods[] = Enums\HttpMethod::Head;
			}

			// HTTP OPTIONS is always allowed.
			if(!in_array(Enums\HttpMethod::Options, $allowedHttpMethods)){
				$allowedHttpMethods[] = Enums\HttpMethod::Options;
			}

			// If this file is `PATCH`, `PUT`, or `DELETE`, then we don't allow `POST` at this endpoint.
			// E.g. if this file is `PATCH /employees/123` then we don't allow `POST /employees/123` (instead, we should `POST /employees`)...
			// TODO ...but, we must tunnel non-`GET` requests submitted via HTML forms using `POST`. So, always allow `POST` in those cases. For now, this block is commented out until we ascend to the nirvana of HTML forms allowing non-`POST` methods. See <https://github.com/whatwg/html/pull/11347>.
			/*
			if(
				in_array(Enums\HttpMethod::Delete, $allowedHttpMethods)
				||
				in_array(Enums\HttpMethod::Patch, $allowedHttpMethods)
				||
				in_array(Enums\HttpMethod::Put, $allowedHttpMethods)
			){
				$newMethods = [];
				foreach($allowedHttpMethods as $method){
					if($method != Enums\HttpMethod::Post){
						$newMethods[] = $method;
					}
				}
				$allowedHttpMethods = $newMethods;
			}
			*/
			// See above... if we allow `DELETE`, `PATCH`, or `PUT`, allow tunneling through `POST`.
			if(
				!in_array(Enums\HttpMethod::Post, $allowedHttpMethods)
				&&
				(
					in_array(Enums\HttpMethod::Delete, $allowedHttpMethods)
					||
					in_array(Enums\HttpMethod::Patch, $allowedHttpMethods)
					||
					in_array(Enums\HttpMethod::Put, $allowedHttpMethods)
				)
			){
				$allowedHttpMethods[] = Enums\HttpMethod::Post;
			}

			// Sort the final array.
			usort($allowedHttpMethods, fn(BackedEnum $a, BackedEnum $b): int => strcasecmp((string)$a->value, (string)$b->value));

			$this->_AllowedHttpMethods = $allowedHttpMethods;
		}

		return $this->_AllowedHttpMethods;
	}

	/**
	 * Calculate the allowed HTTP methods for the currently running script and output HTTP headers advertising them.
	 *
	 * @param ?array<Enums\HttpMethod> $allowedHttpMethods Only allow these methods, or `null` to calculate the allowed methods based on the presence/absence of `http-*.php` files.
	 */
	private function OutputAllowedHttpMethods(?array $allowedHttpMethods = null): void{
		$allowedHttpMethods = $allowedHttpMethods ?? $this->GetAllowedHttpMethods();

		if(sizeof($allowedHttpMethods) > 0){
			header('allow: ' . implode(',', array_map(fn($httpMethod): string => $httpMethod->value, $allowedHttpMethods)));
		}

		if(in_array(Enums\HttpMethod::Patch, $allowedHttpMethods)){
			header('accept-patch: application/x-www-form-urlencoded,multipart/form-data');
		}

		if(in_array(Enums\HttpMethod::Post, $allowedHttpMethods)){
			header('accept-post: application/x-www-form-urlencoded,multipart/form-data');
		}
	}
}
