#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use function Safe\getopt;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]delete-banned-ip-addresses[/]',
		description: 'Delete banned IP addresses that are more than one month old.',
	);
}

$restIndex = 0;
$options = getopt('h', ['help'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) != 0){
	Usage();
}

// Turn off the slow query log for this session.
Db::Query('set session slow_query_log = 0');

Db::Query('delete from BannedIpAddresses where CreatedAt < utc_timestamp() - interval 1 month');
