#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use function Safe\getopt;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]delete-newsletter-subscriptions[/]',
		description: 'Delete expired newsletter subscriptions and newsletter signup attempts.',
	);
}

$restIndex = 0;
$options = getopt('h', ['help'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) != 0){
	Usage();
}

// Turn off the slow query log for this session.
Db::Query('set session slow_query_log = 0');

// Delete unconfirmed `NewsletterSubscription`s that are more than a week old, and any deleted `NewsletterSubscription`s.
Db::Query('
		delete
		from NewsletterSubscriptions
		where
			(
				IsConfirmed = false
				and
				datediff(utc_timestamp(), CreatedAt) >= 7
			)
			or
			(
				IsVisible = false
				and
				datediff(utc_timestamp(), UpdatedAt) >= 1
			)
		');

// Delete signup attempts after one month.
Db::Query('delete from NewsletterSignupAttempts where CreatedAt < utc_timestamp() - interval 1 month');
