#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use function Safe\getopt;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]delete-newsletter-subscriptions[/]',
		description: 'Delete unconfirmed newsletter subscriptions that are more than a week old, and any confirmed newsletter subscriptions that are marked for deletion.',
	);
}

$restIndex = 0;
$options = getopt('h', ['help'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) != 0){
	Usage();
}

// Turn off the slow query log for this session.
Db::Query('set session slow_query_log = 0');

// Delete unconfirmed `NewsletterSubscription`s that are more than a week old, and any deleted `NewsletterSubscription`s.
Db::Query('
		DELETE
		from NewsletterSubscriptions
		where
			(
				IsConfirmed = false
				and
		    		datediff(utc_timestamp(), Created) >= 7
		    	)
		    	or
		    	(
		    		IsVisible = false
		    		and
		    		datediff(utc_timestamp(), Updated) >= 1
		    	)
	');
