#!/usr/bin/php
<?
require_once('/standardebooks.org/web/lib/Core.php');

// Delete unconfirmed newsletter subscribers who are more than a week old.
Db::Query('
		DELETE
		from NewsletterSubscriptions
		where IsConfirmed = false
		    and datediff(utc_timestamp(), Created) >= 7
	');
