#!/standardebooks.org/web/.venv/bin/python

import argparse
import html
import os
import se
import se.easy_xml
import se.se_epub
from se.se_help_formatter import SeHelpFormatter

# Require arguments.
parser = argparse.ArgumentParser(description="Inject a navigation footer into XHTML files of a Standard Ebook.", formatter_class=SeHelpFormatter)
parser.add_argument("ebook_dir", metavar="SE_EBOOK_REPO_DIRECTORY", type=str, help="The path to the main directory of the ebook.")
parser.add_argument("book_url", metavar="URL", type=str, help="The ebook URL.")
args = parser.parse_args()

ebook_dir = args.ebook_dir
book_url = args.book_url

# Make an instance of the SeEpub class so we can use helper functions to easily get spine.
se_epub = se.se_epub.SeEpub(ebook_dir)

# Get spine paths.
spine_paths = se_epub.spine_file_paths

# Make sure spine paths are of the form `text/chapter-1.xhtml`, with no leading `/`.
rel_spine_paths = ["/".join(str(path).split("/")[str(path).split("/").index("text"):]).lstrip("/") for path in spine_paths]

# Get titles from spine.
spine_titles = [se.easy_xml.EasyXmlTree(open(file_path).read()).xpath("//head/title/text()", str)[0] for file_path in spine_paths]

# Make list of dicts containing title and relative path for each file.
chapter_links = [{"title": title, "path": path} for title, path in zip(spine_titles, rel_spine_paths)]

# Create helper function for getting filename without extension.
def get_filename_without_extension(dict_with_path):
	return os.path.splitext(dict_with_path["path"])[0] if dict_with_path else ""

# Create footers.
for i, chapter_link in enumerate(chapter_links):
	previous_dict = chapter_links[i - 1] if i > 0 else None
	next_dict = chapter_links[i + 1] if i < len(chapter_links) - 1 else None

	file_path = os.path.join(ebook_dir, "src/epub", chapter_link["path"])

	previous_link_filename, next_link_filename = [get_filename_without_extension(chapter_dict) for chapter_dict in [previous_dict, next_dict]]

	with open(file_path, "r") as file:
		chapter = file.read()

	previous_link = f"""<a href="{book_url}/{previous_link_filename}" rel="prev"><i>Previous:</i> {html.escape(previous_dict["title"])}</a>""" if previous_dict else ""
	next_link = f"""<a href="{book_url}/{next_link_filename}" rel="next"><i>Next:</i> {html.escape(next_dict["title"])}</a>""" if next_dict else ""

	footer = f"<footer><ul><li>{previous_link}</li><li>{next_link}</li></ul></footer>"
	chapter = chapter.replace("</body>", f"{footer}</body>")

	with open(file_path, "w") as file:
		file.write(chapter)
