#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use function Safe\getopt;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]pending-payments-watchdog[/]',
		description: 'Send an email to S.E. administrators if there are any pending payments which seem to have failed processing.',
	);
}

$restIndex = 0;
$options = getopt('h', ['help'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) != 0){
	Usage();
}

$pendingPayments = Db::Query('
				SELECT *
				from PendingPayments
				where ProcessedOn is not null
			');

if(sizeof($pendingPayments) > 0){
	$em = new QueuedEmailMessage();
	$em->To = ADMIN_EMAIL_ADDRESS;
	$em->From = ADMIN_EMAIL_ADDRESS;
	$em->Subject = 'Unprocessed payment in database';
	$em->BodyHtml = Template::EmailAdminUnprocessedDonations();
	$em->BodyText = Template::EmailAdminUnprocessedDonationsText();
	$em->Send();
}
