#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use function Safe\getopt;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]rebuild-search-db[/] [[flag]--artworks-only[/] | [flag]--ebooks-only[/]]',
		description: 'Truncate and rebuild the Manticore search database.',
		options: [
			[
				'name' => '[flag]--artworks-only[/]',
				'description' => 'Only truncate and rebuild the artworks database.',
			],
			[
				'name' => '[flag]--ebooks-only[/]',
				'description' => 'Only truncate and rebuild the ebooks database.',
			],
		]
	);
}

$restIndex = 0;
$options = getopt('h', ['help', 'artworks-only', 'ebooks-only'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) !== 0 || (isset($options['artworks-only']) && isset($options['ebooks-only']))){
	Usage();
}

$rebuildEbooks = true;
$rebuildArtworks = true;

if(isset($options['artworks-only'])){
	$rebuildEbooks = false;
	$rebuildArtworks = true;
}
elseif(isset($options['ebooks-only'])){
	$rebuildEbooks = true;
	$rebuildArtworks = false;
}

try{
	// Confirm that Manticore is running.
	SearchDb::Connect();

	if($rebuildEbooks){
		print("Rebuilding ebooks ...\n");

		SearchDb::Query('TRUNCATE table ebooks');

		$total = Db::QueryInt('SELECT count(*) from Ebooks');

		// Note that more time is spent in MariaDB than in Manticore, so larger result sets make the process faster.
		$increment = 10000;
		$i = 0;

		while(true){
			$ebooks = Db::Query('SELECT * from Ebooks order by EbookId asc limit ?, ?', [$i, $increment], Ebook::class);

			if(sizeof($ebooks) == 0){
				break;
			}

			foreach($ebooks as $ebook){
				$ebook->UpdateSearchRepresentation();
				unset($ebook);
			}

			$i += $increment;
			$percent = $total == 0 ? 100 : min(100, floor(($i / $total) * 100));
			print("Ebooks \t" . min($total, $i) . "/" . $total . "\t" . $percent . "%\n");
		}
	}

	if($rebuildArtworks){
		print("Rebuilding artworks ...\n");

		SearchDb::Query('TRUNCATE table artworks');

		$total = Db::QueryInt('SELECT count(*) from Artworks');

		// Note that more time is spent in MariaDB than in Manticore, so larger result sets make the process faster.
		$increment = 10000;
		$i = 0;

		while(true){
			$artworks = Db::Query('SELECT * from Artworks order by ArtworkId asc limit ?, ?', [$i, $increment], Artwork::class);

			if(sizeof($artworks) == 0){
				break;
			}

			foreach($artworks as $artwork){
				$artwork->UpdateSearchRepresentation();
				unset($artwork);
			}

			$i += $increment;
			$percent = $total == 0 ? 100 : min(100, floor(($i / $total) * 100));
			print("Artwork \t" . min($total, $i) . "/" . $total . "\t" . $percent . "%\n");
		}
	}
}
catch(Exceptions\DatabaseConnectionFailedException){
	Cli::ExitWithError("Couldn't connect to Manticore.");
}
