#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

usage(){
PrintHelp \
 "[command]$(basename $BASH_SOURCE)[/] [parameter]<FPM_POOL_NAME>[/]" \
 "$(cat << EOF
Reset the PHP-FPM opcache and the APCu user cache for the given PHP-FPM pool without reloading or resetting the PHP-FPM service.
EOF
)"
}

if [ $# -eq 0 ] || { [ $# -eq 1 ] && { [ "$1" = "--help" ] || [ "$1" = "-h" ]; }; }; then
	usage
fi

# If this script is run by a user without sudo powers, they can be given for this command by creating a file in `sudoers.d` with:
#
#     MY_USERNAME ALL=(www-data) NOPASSWD: /usr/bin/env SCRIPT_FILENAME=/tmp/php-fpm-opcache-reset.php REQUEST_METHOD=GET cgi-fcgi -bind -connect *

echo '<?php opcache_reset();?>' > /tmp/php-fpm-opcache-reset.php
sudo --user=www-data env SCRIPT_FILENAME=/tmp/php-fpm-opcache-reset.php REQUEST_METHOD=GET cgi-fcgi -bind -connect "/run/php/$1.sock" &> /dev/null
rm /tmp/php-fpm-opcache-reset.php
