#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use function Safe\getopt;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]send-newsletter-mailings[/]',
		description: 'Send any queued newsletter mailings.',
	);
}

$restIndex = 0;
$options = getopt('h', ['help'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) != 0){
	Usage();
}

Db::Query('set transaction isolation level read committed');
Db::Query('start transaction');
Db::Query('set @start = utc_timestamp()');
$newsletterMailings = Db::Query('SELECT * from NewsletterMailings force index(idxStatus) where Status = ? and SendOn <= @start for update skip locked', [Enums\QueueStatus::Queued], NewsletterMailing::class);
Db::Query('UPDATE NewsletterMailings set Status = ? where Status = ? and SendOn <= @start', [Enums\QueueStatus::Processing, Enums\QueueStatus::Queued]);
Db::Query('commit');

foreach($newsletterMailings as $newsletterMailing){
	print('Sending newsletter mailing #' . $newsletterMailing->NewsletterMailingId . "\n");
	$newsletterMailing->Send();
}
