#! /usr/bin/env bash
set -e
set -o pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

usage(){
PrintHelp \
 "[command]$(basename $BASH_SOURCE)[/] [-v,-vv,--verbosity [parameter]{1 | 2}[/]] [-n,--new-only | -u,--update-only] [-s,--start-letter [parameter]<LETTER>[/]] [--token [parameter]<TOKEN>[/]] [path][parameter]<DIRECTORY>[/]" \
 "$(cat << EOF
Syncs books from the [url]standardebooks.org[/] GitHub organization to [path][parameter]<DIRECTORY>[/].

GNU versions of [command]grep[/] and [command]sed[/] are required. If you're on a Mac, you'll need to install GNU versions (via Homebrew, MacPorts, etc.) and make sure they're first in your path.
EOF
)"\
 "$(cat << EOF
-b,--bare

	Clone bare repositories instead of working directories; useful when called on a server.


-n,--new-only

	Only download new repositories, don't update existing ones.


-s,--start-letter [parameter]<LETTER>[/]

	Skip repositories starting with letters prior to the specified letter.


--token [parameter]<TOKEN>[/]

	Specify a GitHub access token to use for request; useful when hitting GitHub's rate limit.


-u,--update-only

	Only update existing repositories, don't download new ones.


-v,--verbosity [parameter]1[/]

	Display general progress updates.


-vv,--verbosity [parameter]2[/]

	Display general progress updates and verbose [command]git[/] output.
EOF
)"
}

check_arg(){
	case "$2" in
		''|$1) ExitWithError "$3" ;;
	esac
}

# strpos X Y, return position of substring Y in string X
str_pos(){
	x="${1%%"$2"*}"
	[[ "$x" = "$1" ]] && echo -1 || echo "${#x}"
}
# end functions

# Terminate on CTRL-C
trap ctrl_c INT
ctrl_c() {
	exit
}

require "git"

if [ $# -eq 0 ] || { [ $# -eq 1 ] && { [ "$1" = "--help" ] || [ "$1" = "-h" ]; }; }; then
	usage
fi

LETTERS="abcdefghijklmnopoqrstuvwxyz"
verbosity=0
newUpdate=""
githubToken=""
target=""
bare=""
startLetter=""
startPos=-1

# process each of the parameters one at a time, shifting each time to get the next one
while [ $# -gt 0 ]; do
	case "$1" in
		-b|--bare)
			bare="--mirror"
			shift 1
			;;
		-n|--new-only)
			newUpdate="new"
			shift 1
			;;
		-u|--update-only)
			newUpdate="update"
			shift 1
			;;
		-s|--start-letter)
			check_arg '*[!b-z]*' "$2" "--start-letter is not a lowercase letter greater than [parameter]a[/]."
			startLetter="$2"
			shift 2
			;;
		-v)
			verbosity=1
			shift 1
			;;
		-vv)
			verbosity=2
			shift 1
			;;
		--verbosity)
			check_arg '*[!0-9]*' "$2" "Verbosity is not a positive integer."
			verbosity="$2"
			shift 2
			;;
		--token)
			check_arg '*[!0-9a-zA-Z_]*' "$2" "Token is empty or contains illegal characters."
			githubToken="$2"
			shift 2
			;;
		*)
			break ;;
	esac
done

if [ $# -ne 1 ] || [ -z "$1" ]; then
	usage
fi

target="$1"

if ! [ -d "${target}" ]; then
	ExitWithError "[path]${target}[/] isn't a directory."
fi

if ! cd "${target}"; then
	ExitWithError "Couldn’t enter [path]${target}[/]."
fi

if [ "${startLetter}" != "" ]; then
	startPos=$(str_pos "${LETTERS}" "${startLetter}")
fi

# update any existing repositories
if [ "${newUpdate}" != "new" ]; then
	if [ "${verbosity}" -gt 0 ]; then
		printf "Updating local repositories ... \n"
	fi

	for item in ./*/; do
		# if starting letter specified, make sure we're past it
		if [ $startPos -gt 0 ]; then
			repName=$(basename "${item}")
			repLetter="${repName:0:1}"
			repPos=$(str_pos "${LETTERS}" "${repLetter}")
			if [ $repPos -lt $startPos ]; then
				continue
			fi
		fi
	
		[ -e "${item}" ] || break

		if [ "${verbosity}" -gt 0 ]; then
			printf "Updating %s ... " "${item}"
		fi

		# if it's not a repository directory, skip it
		git -C "${item}" rev-parse > /dev/null 2>&1 || continue

		# this works whether the repository is bare or a working directory
		if [ "${verbosity}" -lt 2 ]; then
			git -C "${item}" fetch -q
		else
			git -C "${item}" fetch -v
		fi

		if [ "${verbosity}" -gt 0 ]; then
			printf "Done.\n"
		fi
	done
fi

if [ "${newUpdate}" = "update" ]; then
	exit
fi

# clone the remaining repositories
if [ "${verbosity}" -gt 0 ]; then
	printf "Cloning remote repositories ... \n"
	printf "Fetching repository urls ..."
fi

# get all of the repository names from the GitHub API, one "page" at a time
url="https://api.github.com/orgs/standardebooks/repos?per_page=100"
repoUrls=""

while true; do
	# get a "page" worth of repository URL's
	if [ -n "${githubToken}" ]; then
		response=$(curl -H "Authorization: token ${githubToken}" -si "${url}") ||
			ExitWithError "Curl request failed."
	else
		response=$(curl -si "${url}") ||
			ExitWithError "Curl request failed."
	fi

	if printf "%s" "${response}" | grep -q "^X-RateLimit-Remaining: 0$"; then
		limitReset=$(printf "%s" "${response}" | grep -oP "^X-RateLimit-Reset: \K[0-9]+$")
		printf "You have reached your daily allowance for unauthenticated GitHub API requests.\n\
			Either wait until %s or use an OAuth token.\n\
			You can create a new token at <https://github.com/settings/tokens/new> and \
			pass it to this script with the --token option.\n\
			The token does not need any permissions.\n" "$(date -d @"${limitReset}")" 1>&2
		exit
	fi

	# parse the response to get the current page's URL's
	currentRepoUrls=$(printf "%s" "${response}" | awk 'BEGIN { FS="\""; RS="," }; { if ($2 == "clone_url") {print $4} }')
	# add them to the full list in repoUrls
	repoUrls=$(printf "%s\n%s" "${repoUrls}" "${currentRepoUrls}")
	# set the variable to get the next "page"
	url=$(printf "%s" "${response}" | grep -oP "<\Khttps://api.github.com/[^>]*(?=>; rel=\"next\",)") || break

	if [ "${verbosity}" -gt 0 ]; then
		printf "."
	fi
done

if [ "${verbosity}" -gt 0 ]; then
	printf " Done.\n"
fi

# skip the non-ebook repositories by removing their names from the list
repoUrls=$(printf "%s" "${repoUrls}" | grep -v -e "/tools.git\$" -e "/web.git\$" -e "/manual.git\$" -e "/standard-blackletter.git\$" -e "/sublime-text-se-plugin.git\$" | awk 'NF')

# process the list, reading one repository at a time
printf "%s\n" "${repoUrls}" | while IFS= read -r repoUrl; do
	# make sure it's not an empty string
	[ -n "${repoUrl}" ] || continue

	# strip everything prior to the last segment of the name
	repoName="${repoUrl##*/}"
	if [ "${bare}" = "" ]; then
		repoName="${repoName%.git}"
	fi

	# if the repo already exists, skip it (handled in the update above)
	[ -d "${repoName}" ] && continue

	# if the repository name has been truncated due to GitHub's name length limits,
	# but a local clone with the full name exists, don't attempt to clone it again
	repoNameLength=$(printf "%s" "${repoName%.git}" | wc -m)
	if [ "${repoNameLength}" -ge 100 ]; then
		if dirs=( "${repoName%.git}"*/ ) && [[ -d ${dirs[0]} ]]; then
			continue
		fi
	fi

	if [ "${verbosity}" -gt 0 ]; then
		printf "Cloning %s ... \n" "${repoUrl}"
	fi

	# clone the repository, creating either a bare or working directory based on the option
	if [ "${verbosity}" -lt 2 ]; then
		git clone -q ${bare} "${repoUrl}"
	else
		git clone -v ${bare} "${repoUrl}"
	fi

	# if a directory with the repository name doesn't exist, the clone did not complete successfully
	if ! [ -d "${repoName}" ]; then
		printf "Failed to clone %s.\n" "${repoName}." 1>&2
	elif [ "${verbosity}" -gt 0 ]; then
		printf "Done.\n"
	fi

	# if the repository doesn't have a metadata file, skip to the next repository
	metadata=$(git -C "${repoName}" show HEAD:src/epub/content.opf > /dev/null 2>&1) || continue

	# get the last segment of the dc:identifier from the metadata
	properName="$(git -C "${repoName}" show HEAD:src/epub/content.opf |
		grep -oE "<dc:identifier id=\"uid\">https://standardebooks.org/ebooks/[^<]+</dc:identifier>" |
		sed -E "s/<[^>]+?>//g" |
		sed -E "s|https://standardebooks.org/ebooks/||g" |
		sed -E "s|/|_|g").git"
	if [ "${bare}" = "" ]; then
		properName="${properName%.git}"
	fi

	# if the repository name isn't the same as the identifier (GitHub has a size limitation on
	# the length of a repo name; works with a lot of translators can exceed it), rename the 
	# directory to be the identifier name
	if [ "${repoName}" != "${properName}" ]; then
		if [ -d "${properName}" ]; then
			if [ "${verbosity}" -gt 0 ]; then
				printf "Not moving %s to %s: directory exists\n" "${repoName}" "${properName}"
			fi
		else
			if [ "${verbosity}" -gt 0 ]; then
				printf "Moving %s to %s\n" "${repoName}" "${properName}"
			fi
			mv "${repoName}" "${properName}"
		fi
	fi
done
