#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use function Safe\getopt;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]update-ebook-database[/] [[flag]-v[/],[flag]--verbose[/]] [path][parameter]<SE_EBOOK_WEB_DIRECTORY>[/]',
		description: 'Update the database entry for the ebook at the target ebook web path, e.g. [path]/standardebooks.org/web/www/ebooks/a-a-milne/the-red-house-mystery[/].',
		arguments: [
			[
				'name' => '[path][parameter]<SE_EBOOK_WEB_DIRECTORY>[/]',
				'description' => 'The path to the ebook web directory to update.',
			],
		],
		options: [
			[
				'name' => '[flag]-v[/],[flag]--verbose[/]',
				'description' => 'Increase output verbosity.',
			],
		]
	);
}

$restIndex = 0;
$options = getopt('hv', ['help', 'verbose'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);
$ebookWwwFilesystemPath = $parameters[0] ?? null;
$verbose = isset($options['v']) || isset($options['verbose']);

if(sizeof($parameters) !== 1 || $ebookWwwFilesystemPath === null){
	Usage();
}

try{
	$ebook = Ebook::FromFilesystem($ebookWwwFilesystemPath);

	if($verbose){
		print("Title: $ebook->Title\n");
		print("Identifier: $ebook->Identifier\n");
	}

	$ebook->CreateOrUpdate();

	// If there was an `EbookPlaceholder` for this ebook, delete it.
	$ebook->EbookPlaceholder?->Delete();

	// If there was a `Project` for this ebook, mark it as completed.
	if($ebook->ProjectInProgress !== null){
		$ebook->ProjectInProgress->Status = Enums\ProjectStatusType::Completed;
		$ebook->ProjectInProgress->Ended = NOW;
		$ebook->ProjectInProgress->Save();
	}
}
catch(Exceptions\AppException $ex){
	Cli::ExitWithError("An exception occurred when updating the ebook database:\n\t" . get_class($ex) . ": " . $ex->getMessage());
}
