#!/usr/bin/php
<?
require_once('/standardebooks.org/web/lib/Core.php');

use function Safe\getopt;

$longopts = ['ebookWwwFilesystemPath:', 'verbose'];
$options = getopt('v', $longopts);

$ebookWwwFilesystemPath = $options['ebookWwwFilesystemPath'] ?? null;

$verbose = false;
if(isset($options['v']) || isset($options['verbose'])){
	$verbose = true;
}

if($ebookWwwFilesystemPath === null){
	print("Expected usage: update-ebook-database [-v,--verbose] --ebookWwwFilesystemPath <path>\n");
	exit(1);
}

if($verbose){
	print("ebookWwwFilesystemPath: $ebookWwwFilesystemPath\n");
}

$ebook = new Ebook($ebookWwwFilesystemPath);

if($verbose){
	print("Title: $ebook->Title\n");
	print("Identifier: $ebook->Identifier\n");
}

$ebook->CreateOrUpdate();
