#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use Safe\DateTimeImmutable;
use function Safe\getopt;
use function Safe\set_time_limit;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]update-project-statuses[/]',
		description: 'Update active ebook project statuses based on recent activity.',
	);
}

$restIndex = 0;
$options = getopt('h', ['help'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) != 0){
	Usage();
}

set_time_limit(0);

/**
 * Iterate over all active `Project`s and update statuses based on the latest known activity.
 *
 * If the last activity was more than 30 days old, mark the `Project` as stalled and send a reminder email.
 *
 * 60 days after the reminder email, the `Project` is marked as abandoned if there has not been any activity since.
 *
 * If a `Project` stalls and is re-activated, the process will repeat except no further reminder emails will be sent.
 */

/** @var array<Project> $projects */
$projects = Project::GetAllByStatuses([Enums\ProjectStatusType::InProgress, Enums\ProjectStatusType::AwaitingReview, Enums\ProjectStatusType::Reviewed, Enums\ProjectStatusType::Stalled]);

$oldestStalledTimestamp = new DateTimeImmutable('60 days ago');
$oldestAbandonedTimestamp = new DateTimeImmutable('60 days ago');

foreach($projects as $project){
	if($project->IsStatusAutomaticallyUpdated){
		if(
			(
				$project->Status == Enums\ProjectStatusType::InProgress
				||
				$project->Status == Enums\ProjectStatusType::AwaitingReview
				||
				$project->Status == Enums\ProjectStatusType::Reviewed
			)
			&&
			$project->LastActivityTimestamp < $oldestStalledTimestamp
		){
			// An active `Project` has stalled.
			$project->Status = Enums\ProjectStatusType::Stalled;

			// Send an email to the producer.
			$project->SendReminder(Enums\ProjectReminderType::Stalled);
		}
		elseif(
			$project->Status == Enums\ProjectStatusType::Stalled
			&&
			$project->LastActivityTimestamp >= $oldestStalledTimestamp
		){
			// Revive previously-stalled `Project`s.
			$project->Status = Enums\ProjectStatusType::InProgress;
		}
		elseif(
			$project->Status == Enums\ProjectStatusType::Stalled
			&&
			$project->LastActivityTimestamp < $oldestStalledTimestamp
			&&
			$project->GetReminder(Enums\ProjectReminderType::Stalled)?->Created < $oldestAbandonedTimestamp
		){
			// A stalled `Project` is now abandoned.
			$project->Status = Enums\ProjectStatusType::Abandoned;

			// Set the corresponding `EbookPlaceholder` to not be "in progress" any more.
			if($project->Ebook->EbookPlaceholder !== null){
				try{
					$project->Ebook->EbookPlaceholder->IsInProgress = false;
					$project->Ebook->EbookPlaceholder->Save();
				}
				catch(Exceptions\EbookPlaceholderInvalidException){
					// Pass.
				}
			}

			// Send a notification to the producer.
			$project->SendReminder(Enums\ProjectReminderType::Abandoned);
		}
	}

	$project->Save();
}
