#!/usr/bin/php
<?
require_once(__DIR__ . '/../lib/Core.php');

use Safe\DateTimeImmutable;
use function Safe\get_cfg_var;
use function Safe\getopt;
use function Safe\preg_match;
use function Safe\preg_match_all;
use function Safe\preg_replace;
use function Safe\set_time_limit;

function Usage(): void{
	Cli::PrintHelp(
		usage: '[command]update-project-discussions[/]',
		description: 'Update all active ebook projects with their latest discussion activity.',
	);
}

$restIndex = 0;
$options = getopt('h', ['help'], $restIndex);
$restIndex ??= $argc;

if(isset($options['h']) || isset($options['help'])){
	Usage();
}

$parameters = array_slice($argv, $restIndex);

if(sizeof($parameters) != 0){
	Usage();
}

set_time_limit(0);

/**
 * Check for updated discussion in Google Groups. We can't poll Google Groups discussion pages because 1) they're div soup and it's hard to parse the correct last post date, and 2) Google often blocks our IP for doing automated requests.
 *
 * Instead, we have a special email address subscribed to the S.E. Google Groups mailing list. It receives all email from the group. Then, we use IMAP to poll that email address hourly for unread group messages. We extract the originating message ID from the email headers, and use that to find the project and update its timestamp.
 *
 * We can't use Zoho webhooks because 1) webhooks don't include email headers, which we need for this, and 2) IMAP is more portable to a different email provider in the future.
 *
 * We track *all* message IDs across the entire discussion, because sometimes the root message ID gets lost in the chain. Therefore if any message ID in a given email has been previously recorded, we assume it's part of the chain for this `Project`.
 */

/** @var string $username */
$username = get_cfg_var('se.secrets.zoho.mail.projects_username');
/** @var string $password */
$password = get_cfg_var('se.secrets.zoho.mail.projects_password');

/** @var array<int, object{'Timestamp': \Safe\DateTimeImmutable, 'MessageIds': array<string>, 'SenderEmail': ?string, 'Body': string}> $emailMessageIds An array containing objects, each of which represents one email, its timestamp, sender, body, and all the related message IDs in its headers. */
$emailMessageIds = [];

try{
	$mailbox = new PhpImap\Mailbox('{imappro.zoho.com:993/imap/ssl}INBOX', $username, $password);
	// Expunge deleted mails upon mailbox close.
	$mailbox->setConnectionArgs(CL_EXPUNGE);

	// See <https://php.net/manual/en/function.imap-search.php>.
	$emailIds = $mailbox->searchMailbox('ALL');

	foreach($emailIds as $emailId){
		$email = $mailbox->getMail($emailId);

		if(
			preg_match('/\bstandardebooks@googlegroups\.com\b/iu', $email->toString ?? '')
			&&
			$email->messageId !== null
		){
			// Extract all message IDs present in various headers we're interested in.
			$headerString = trim($email->messageId . ' ' . ($email->headers->references ?? '') . ' ' . ($email->headers->in_reply_to ?? ''));
			preg_match_all('/<([^<>\s@]+?@[^<>\s@]+?)>/iu', $headerString, $matches);
			$messageIds = array_values(array_unique($matches[1]));

			if(sizeof($messageIds) > 0){
				// Get the timestamp of this email.
				$timestamp = NOW;
				if($email->date !== null){
					try{
						$timestamp = new DateTimeImmutable($email->date);
					}
					catch(\Throwable){
						// Pass.
					}
				}

				$object = new stdClass();
				$object->Timestamp = $timestamp;
				$object->MessageIds = $messageIds;
				$object->SenderEmail = $email->fromAddress !== null ? strtolower($email->fromAddress) : null;
				// Store the plain text body without any quoted text.
				$object->Body = preg_replace('/^>.+$/u', '', trim($email->textPlain));
				$emailMessageIds[] = $object;
			}
		}

		$mailbox->markMailAsRead($emailId);
		$mailbox->moveMail($emailId, 'Trash');
	}
}
catch(\Exception $ex){
	$log = new Log();
	$log->Write('Failed connecting to IMAP account: ' . $ex->getMessage());
}

/** @var array<Project> $projects */
$projects = Project::GetAllByStatuses([Enums\ProjectStatusType::InProgress, Enums\ProjectStatusType::AwaitingReview, Enums\ProjectStatusType::Reviewed, Enums\ProjectStatusType::Stalled]);

foreach($projects as $project){
	if(!$project->IsStatusAutomaticallyUpdated){
		continue;
	}

	/** @var array<int, string> $projectDiscussionMessageIds */
	$projectDiscussionMessageIds = [];
	$knownDiscussionMessageIds = $project->GetDiscussionMessageIds();
	$hasMatchedEmail = true;

	// Keep scanning the remaining unmatched emails as long as the previous scan attached at least one new email to a `Project`.
	while($hasMatchedEmail){
		$hasMatchedEmail = false;

		foreach($emailMessageIds as $key => $emailMessage){
			if(array_intersect($knownDiscussionMessageIds, $emailMessage->MessageIds) !== []){
				$knownDiscussionMessageIds = array_values(array_unique(array_merge($knownDiscussionMessageIds, $emailMessage->MessageIds)));
				$projectDiscussionMessageIds = array_merge($projectDiscussionMessageIds, $emailMessage->MessageIds);
				$hasMatchedEmail = true;

				if($project->LastDiscussionTimestamp === null || $project->LastDiscussionTimestamp < $emailMessage->Timestamp){
					$project->LastDiscussionTimestamp = $emailMessage->Timestamp;
				}

				// Is this `Project` ready for review?
				if(
					$project->Reviewer->Email !== null
					&&
					strtolower($project->Producer->Email ?? '') == ($emailMessage->SenderEmail ?? '')
					&&
					$project->Status != Enums\ProjectStatusType::AwaitingReview
					&&
					$project->Status != Enums\ProjectStatusType::Reviewed
					&&
					preg_match('/\b(ready\s+for\s+review|ready\s+to\s+be\s+reviewed|ready\s+for\s+you|this\s+(e?book|project\s+)?is\s+ready[\.\!])\b/iu', $emailMessage->Body)
				){
					$project->Status = Enums\ProjectStatusType::AwaitingReview;

					$em = new QueuedEmailMessage();
					$em->From = ADMIN_EMAIL_ADDRESS;
					$em->To = $project->Reviewer->Email;
					$em->Subject = 'Ebook project ready for review';
					$em->BodyHtml = Template::EmailReviewerProjectReady(project: $project, user: $project->Reviewer);
					$em->Send();
				}

				// We matched this email to a `Project`, remove it from future checks.
				unset($emailMessageIds[$key]);
			}
		}
	}

	$projectDiscussionMessageIds = array_values(array_unique($projectDiscussionMessageIds));

	$project->SaveDiscussionMessages($projectDiscussionMessageIds);
	$project->Save();
}
