# Route requests for a specific resource.
RewriteRule	^/artworks/([^/\.\s]+)$				/artists/http-router.php?artist-url-name=$1

# Route requests for forms applying to a specific resource.
RewriteRule	^/artworks/([^/\.\s]+)/(delete|edit)$		/artists/$2.php?artist-url-name=$1
