# Route requests for a specific resource.
RewriteRule	^/artworks/([^/\.]+)$				/artists/http-router.php?artist-url-name=$1

# Route requests for forms applying to a specific resource.
RewriteRule	^/artworks/([^/\.]+?)/(delete|edit)$		/artists/$2.php?artist-url-name=$1
