RewriteRule	^/artworks/([^/\.]+)$				/artists/http-router.php?artist-url-name=$1 [B,L]

RewriteRule	^/artworks/([^/\.]+?)/delete$			/artists/delete.php?artist-url-name=$1 [B,L]

RewriteRule	^/artworks/([^/\.]+)/([^/\.]+)$			/artworks/http-router.php?artist-url-name=$1&artwork-url-name=$2 [B,L]

RewriteRule	^/artworks/([^/\.]+)/([^/\.]+)/edit$		/artworks/edit.php?artist-url-name=$1&artwork-url-name=$2 [B,L]
