# Route requests for a specific resource.
RewriteRule	^/artworks/([^/\.]+)/([^/\.]+)$				/artworks/http-router.php?artist-url-name=$1&artwork-url-name=$2

# Route requests for forms applying to a specific resource.
RewriteRule	^/artworks/([^/\.]+)/([^/\.]+)/(delete|edit)$		/artworks/$3.php?artist-url-name=$1&artwork-url-name=$2
