# Route requests for a specific resource.
RewriteRule	^/artworks/([a-z0-9\-]+)/([a-z0-9\-]+)$			/artworks/http-router.php?artist-url-name=$1&artwork-url-name=$2

# Route requests for forms applying to a specific resource.
RewriteRule	^/artworks/([a-z0-9\-]+)/([a-z0-9\-]+)/(delete|edit)$	/artworks/$3.php?artist-url-name=$1&artwork-url-name=$2
