RewriteRule	^/blog($|/.+$)					/blog-posts$1 [N,QSA]

RewriteRule	^/blog-posts/([^/\.]+)$				/blog-posts/http-router.php?blog-post-url-title=$1 [L]

RewriteRule	^/blog-posts/([^/\.]+)/edit$			/blog-posts/edit.php?blog-post-url-title=$1 [L]
