# Rewrite `/blog/*` to `blog-posts/*`.
RewriteRule	^/blog($|/.+$)					/blog-posts$1 [QSA]

# Route requests for a specific resource.
RewriteRule	^/blog-posts/([^/\.]+)$				/blog-posts/http-router.php?blog-post-url-title=$1

# Route requests for forms applying to a specific resource.
RewriteRule	^/blog-posts/([^/\.]+)/(delete|edit)$		/blog-posts/$2.php?blog-post-url-title=$1
