# Work around some naughty hotlinkers.
RewriteCond	%{HTTP_REFERER} !^$
RewriteCond	%{HTTP_REFERER} ^https?://.*medialibrary.it [NC]
RewriteRule	^(/ebooks/.+/downloads/|/images/covers/)	/images/do-not-hotlink.jpg [R=301,NC]

# Redirect cover images with caching SHA's to the root image.
# We do this because some sites like Google cache the cover image path, so changing it results in lots of 404s.
RewriteRule	^/images/covers/(.+?)\-[a-z0-9]{8}\-(cover|hero)(@2x)?\.(jpg|avif)$	/images/covers/$1-$2$3.$4

# Route collections an `Ebook` is a member of. Useful for admin purposes.
RewriteRule	^/ebooks/(.+?)/collections$		/ebooks/collections.php?url-path=$1 [QSA]

# Misc ebook rewrites.
RewriteRule	^/ebooks/(.+?)/(delete|edit)$		/ebook-placeholders/$2.php?url-path=$1
RewriteRule	^/subjects/([^\./]+?)$			/ebooks/index.php?tags[]=$1 [B,QSA]
RewriteRule	^/ebooks/([^\./]+?)/downloads$		/bulk-downloads/http-router.php?author-url-name=$1 [QSA]
RewriteRule	^/ebooks/([^\./]+?)/feeds$		/feeds/http-router.php?author-url-name=$1 [QSA]
RewriteRule	^/collections/([^\./]+?)$		/collections/http-router.php?collection-url-name=$1 [QSA]
RewriteRule	^/collections/([^/]+?)/downloads$	/bulk-downloads/http-router.php?collection-url-name=$1
RewriteRule	^/collections/([^/]+?)/feeds$		/feeds/http-router.php?collection-url-name=$1

# Route downloads for distributable ebook files.
RewriteRule	^/ebooks/(.+?)/downloads/(.+?\.(?:epub|azw3))$	/ebooks/download.php?url-path=$1&filename=$2 [QSA]

# Route published ebook pages, but prevent this rule from firing if we're getting a distributable ebook file.
# Sometimes links in the wild incorrectly include spaces, so use the `B` flag to return a 404 instead of a 403.
RewriteCond	%{REQUEST_METHOD}		^GET|HEAD$
RewriteCond	%{REQUEST_FILENAME}		!^/ebooks/.+?/downloads/.+$
RewriteCond	%{REQUEST_FILENAME}		!^/ebooks/.+?/text.*$
RewriteCond	%{REQUEST_FILENAME}		!^/ebooks/.+?/projects.*$
RewriteRule	^/ebooks/([^\.\s]+?)$		/ebooks/http-router.php?url-path=$1

RewriteCond	%{REQUEST_METHOD}		!^GET$
RewriteRule	^/ebooks/([^\.\s]+?)$		/ebook-placeholders/http-router.php?url-path=$1
