# Redirect old feed URLs.
RewriteRule	^/(opds|rss|atom)(.*)$				/feeds/$1$2 [R=301]

# Rewrite search pages for feeds.
RewriteCond	%{QUERY_STRING}	\bquery=
RewriteRule	^/feeds/(opds|atom|rss)/all\.xml$		/feeds/search.php?feed-format-type=$1 [QSA]

RewriteRule	^/feeds/(atom|rss)/([^/\.]+)$			/feeds/collection.php?feed-format=$1&collection-type=$2

RewriteRule 	^/feeds/(.+\.xml)$				/feeds/download.php?path=$1
