# Favicon rewrites.
RewriteRule	^/(apple-touch|android-chrome|favicon|mstile|safari-pinned|browserconfig|manifest)([^/]+)$	/images/favicons/$1$2

# Redirect the toolset to GitHub.
RewriteRule	^/tools$	https://github.com/standardebooks/tools [R=302,L]

# Redirect latest version of the manual.
RewriteRule	^/manual/latest([^\s]*)	/manual/index.php?url=$1

# Rewrite rules for bulk downloads.
RewriteRule 				^/bulk-downloads/([^\s]+\.zip)$		/bulk-downloads/download.php?path=$1

# Don't allow non-`.zip` requests that are deeper than one directory to fall through to the default PHP file handler, which will log an error because the bulk downloads folder is symlinked in our filesystem.
RewriteRule 				^/bulk-downloads/[^/\.\s]+/.+$		- [R=404,L]
RewriteRule 				^/bulk-downloads/([^/\.\s]+)$		/bulk-downloads/collection.php?label-type=$1
