RewriteRule	^/newsletter$							/newsletter-subscriptions/new.php [L]
RewriteRule	^/users/([^/\.]+?)/newsletter-subscriptions$			/newsletter-subscriptions/http-get.php?user-identifier=$1 [L]
RewriteRule	^/users/([^/\.]+?)/newsletter-subscriptions/confirm$		/newsletter-subscriptions/confirm.php?user-identifier=$1 [L]
RewriteRule	^/users/([^/\.]+?)/newsletter-subscriptions/([\d]+)/delete$	/newsletter-subscriptions/delete.php?user-identifier=$1&newsletter-id=$2 [L]

RewriteRule	^/newsletter-mailings/([\d]+)$					/newsletter-mailings/http-router.php?newsletter-mailing-id=$1 [L]

RewriteRule	^/newsletter-mailings/([\d]+)/edit$				/newsletter-mailings/edit.php?&newsletter-mailing-id=$1 [L]
