# Route requests for a `Poll`.
RewriteRule	^/polls/([^/\.]+)$				/polls/http-router.php?poll-url-name=$1

# Route requests for forms applying to a specific resource.
RewriteRule	^/polls/([^/\.]+)/votes/new$			/poll-votes/new.php?poll-url-name=$1

# Route requests for a `PollVote'.
RewriteRule	^/polls/([^/\.]+)/votes/([0-9]+)$		/poll-votes/http-router.php?poll-url-name=$1&user-id=$2

# List all `PollVote`s for a given `Poll`.
RewriteCond	%{REQUEST_METHOD} ^GET|HEAD$
RewriteRule	^/polls/([^/\.]+)/votes$			/polls/poll-votes/index.php?poll-url-name=$1

# Route non-GET/HEAD requests for the resource root.
RewriteCond	%{REQUEST_METHOD} !^GET|HEAD$
RewriteRule	^/polls/([^/\.]+)/votes$			/poll-votes/http-router.php?poll-url-name=$1
