RewriteRule				^/polls/([^/\.]+)$				/polls/http-get.php?poll-url-name=$1 [L]
RewriteRule				^/polls/([^/\.]+)/votes/new$			/polls/votes/new.php?poll-url-name=$1 [L]
RewriteRule				^/polls/([^/\.]+)/votes/([0-9]+)$		/polls/votes/http-get.php?poll-url-name=$1&user-id=$2 [L]

RewriteCond expr "%{REQUEST_METHOD} =~ /^GET$/"
RewriteRule				^/polls/([^/\.]+)/votes$			/polls/votes/index.php?poll-url-name=$1 [L]

RewriteCond expr "%{REQUEST_METHOD} !~ /^GET$/"
RewriteRule				^/polls/([^/\.]+)/votes$			/polls/votes/http-router.php?poll-url-name=$1 [L]
