# Form for creating a new `Project` for the given `Ebook`.
RewriteRule	^/ebooks/([^\.]+?)/projects/new$		/projects/new.php?ebook-url-path=$1

# Query string may contain `indent=<BOOL>`.
RewriteRule	^/ebooks/(.+?)/projects/active/reviewer$	/projects/reviewer/http-get.php?url-path=$1 [QSA]

# Route requests for a specific resource.
RewriteRule	^/projects/([\d]+)$				/projects/http-router.php?project-id=$1

# Query string may contain `indent=<BOOL>`.
RewriteRule	^/projects/([\d]+)/reviewer$			/projects/reviewer/http-router.php?project-id=$1 [QSA]

# Route requests for forms applying to a specific resource.
RewriteRule	^/projects/([\d]+)/(delete|edit)$		/projects/$2.php?project-id=$1
