# Route requests for a specific spreadsheet.
RewriteRule	^/spreadsheets/([0-9]+)$			/spreadsheets/http-router.php?spreadsheet-id=$1

# Route requests for forms applying to a specific spreadsheet.
RewriteRule	^/spreadsheets/([0-9]+)/(delete|edit)$		/spreadsheets/$2.php?spreadsheet-id=$1
