RewriteCond	expr "%{REQUEST_METHOD} =~ /^POST|PATCH$/"
RewriteRule	^/users/([\d]+)$				/users/http-router.php?user-id=$1 [L]

# Since we can recieve a URL like `/users/<identifier>`, we have to white list these URLs first.
RewriteRule	^/users/new\.php$				/users/new.php [L]
RewriteRule	^/users/index\.php$				/users/index.php [L]
RewriteRule	^/users/get\.php$				/users/http-get.php [B,L,QSA]

RewriteRule	^/users/([^/]+)$				/users/http-get.php?user-identifier=$1 [B,L]

RewriteRule	^/users/([^/]+)/disambiguation$			/users/disambiguation.php?user-identifier=$1 [B,L]

RewriteRule	^/users/([^/]+)/edit$				/users/edit.php?user-identifier=$1 [B,L]

RewriteRule	^/users/([^/]+)/projects$			/users/projects/index.php?user-identifier=$1 [B,L]
