# Since we can receive a URL like `/users/:user-identifier`, we have to white list these URLs first.
RewriteCond	%{REQUEST_FILENAME} !^/users/new\.php$
RewriteCond	%{REQUEST_FILENAME} !^/users/index\.php$
RewriteCond	%{REQUEST_FILENAME} !^/users/get$
RewriteRule	^/users/([^/]+)$				/users/http-router.php?user-identifier=$1 [B]

# Route requests to jump to to a `User` from the `Users`s index.
RewriteRule	^/users/get$					/users/http-router.php [QSA]

# Route requests to disambiguate several `User`s.
RewriteRule	^/users/([^/]+)/disambiguation$			/users/disambiguation.php?user-identifier=$1 [B]

# Route requests for forms applying to a specific resource.
RewriteRule	^/users/([^/]+)/(delete|edit)$			/users/$2.php?user-identifier=$1 [B]

# Route requests for `Projects` for a `User`.
RewriteRule	^/users/([^/]+)/projects$			/users/projects/index.php?user-identifier=$1 [B]
